### PR TITLE
Group action buttons in edit forms

### PR DESCRIPTION
**Pull request by MrMusic**
In edit forms Joomla! groups 'Save & Close', 'Save & New' and 'Save as Copy' as a dropdown.
group-action-buttons

This pr do this in the same way.

### CODE REVIEW

**Comment by eumel1602** [comment]
When testing, I noticed that the "Save & New" button does not save the images and brings an empty field but brings an error message.
This happens with the pictures, categories and also tags
bildschirmabgriff32

**Comment by MrMusic** [comment]
Thanks for testing @eumel1602 
The cause of this error does not lie in this PR but has been known for some time, see https://github.com/JoomGalleryfriends/JG4-dev/issues/43
As a workaround, a new item must first be saved once.

**Comment by eumel1602** [comment]
OK. Then I couldn't find any more error.
Tested with J4.2.5 / PHP 7.4

**Comment by Elfangor93** [comment]
Testes successfully ✅. Thank you very much.

**Pull request merged**
