### PR TITLE
Database connection problems

### PR DESCRIPTION
**Pull request by Elfangor93**
This PR fixes multiple issues reported in #201.
The following things are added/improved:

- Migration form validation for field `Joomla! path`. Checks, if the folder of the given path exists.
- Migration form validation for database fields. Checks, if a connection to the database is possible with the entered credentials.
- Fixes php error: in_array(): Argument 2 ($haystack) must be of type array, null given

Pendent:

- Migration precheck needs 20 connections to the database

### CODE REVIEW

**Comment by AlexanderSupp** [comment]
I uninstalled the old main and installed this PR.
The test result is the same:
Screenshot 2024-03-02 125454

**Comment by AlexanderSupp** [comment]
Too late. I misunderstand the Swiss English.

Screenshot 2024-03-02 130331

I hope you find a solution.

**Comment by AlexanderSupp** [comment]
I tested this PR on my Windows 11 installation successfully.
My goal was to get the new file structure.
Screenshot 2024-03-03 112156
Screenshot 2024-03-03 112231

**Comment by AlexanderSupp** [comment]
I am a little step forward. The current result is:
 
Screenshot 2024-03-05 220833

**Comment by AlexanderSupp** [comment]
My provider gave me an answer:

For Information:
Guten Tag,
vielen Dank für Ihre Nachricht, gerne helfe ich Ihnen weiter.
Der Wert für max_user_connections ist 50, der Wert kann in Ihrem Tarif leider nicht angepasst werden, diese ist unseren ManagedServer-Tarifen vorbehalten. Der Login via phpmyadmin sollte nicht so viele Verbindungen erzeugen. Wahrscheinlicher ist, das ein ggf. ein Query beim Versuch Ihrer Migration hing, und so nachfolgende aufgestaut hat bis die möglichen Verbindungen erschöpft waren.
Bitte zögern Sie nicht, sich bei Rückfragen oder Problemen jederzeit erneut an uns zu wenden. Wir helfen Ihnen gerne weiter.
Freundliche Grüße
Technical Support

In the meantime, you have solved this problem.

**Comment by AlexanderSupp** [comment]
Last test today, same result. What's about this PR?

After hit Check migration capability:

Screenshot 2024-03-22 182223

**Comment by AlexanderSupp** [comment]
Thank you for quick response and solution.
Migration tested successfully.
2970 images in 137 categories from another Joomla installation with different database and recreate function.
From my point of view, this PR is ready to merge into main.
If this PR is merged and the front end views are also in main, I will test this in the environment of my provider.

**Comment by AlexanderSupp** [comment]
I can't wait. So I started a migration with this PR #203 with status of 24.03.2024, 16:55
Same Joomla Installation: NO
Joomla path localhost to https://Fotofreunde-Much.de
DB-Specification to https://Fotofreunde-Much.de

Target and processed in http://JoomGallery4.Fotofreunde-Much.de
Image usage: Copy

All areas were in the same provider environment by DomainFactory.

136 categories with 3004 images and 135 categories thumbnails were processed successful.
Duration 90 minutes.

Everybody can check the results in both websites.
My strategy of first migrating to Joomla 5.0.3 without JG4 and then migrating JG3.6 to Joomla 5.0.3 works.

**Comment by Elfangor93** [comment]
Many thanks to all the testers!

**Pull request merged**
