### PR TITLE
Fix error during uninstallation v2

### PR DESCRIPTION
**Pull request by Elfangor93**
Fix for issue https://github.com/JoomGalleryfriends/JG4-dev/issues/127

Solves the same problem like PR #128 but removes redundant code parts.
This PR also solves the same issue also in other methods of the installer/uninstaller script.

### CODE REVIEW

**Comment by rowi68** [comment]
Tested ✅ successfully.

**Comment by eumel1602** [comment]
Worked. I was able to uninstall it with no problems

WIN 10 / PHP 8.0.x / J4.3.4 /

**Comment by reni68** [comment]
it works.

**Comment by MrMusic** [comment]
The uninstallation of the component now works without any problems.
However, I noticed that when I reinstalled the component the plugins finder, webservices etc. were no longer installed. Is this a bug or is it intentional?

**Comment by MrMusic** [comment]
Works now without problems. Thank you.

**Pull request merged**
