### PR TITLE
Gallery view – portfolio - infinte scroll

### PR DESCRIPTION
**Pull request by reilldesign**
this pull request is a starting point for the gallery view and shows all images in a grid layout with infite scroll. There are currently no config options and no filter/sorting function.

### CODE REVIEW

**Comment by MrMusic** [comment]
>There are currently no config options and no filter/sorting function.

Thank you very much.
Will these filter/sorting functions be added?

**Comment by reilldesign** [comment]
Filter and sorting options will be added as soon as possible. I just wanted to make sure that the view is noted in the beta. We will discuss the details in the next video conference.

**Comment by Elfangor93** [comment]
@reilldesign This PR is not up to date and does not contain changes you requested and provided in this PR: https://github.com/reilldesign/JG4-dev/pull/1

**Comment by reilldesign** [comment]
I have unfortunately overlooked the new changes and additions and will not be able to bring them together this week. I will only be able to do this next weekend.

**Pull request closed without merging**
