### PR TITLE
Button visability in list views

### PR DESCRIPTION
**Pull request by Elfangor93**
This PR fixes the visability of the buttons in the list views (Issue #237 ).
I had to adjust the access service for that. So please check that the permissions are still correct.

### CODE REVIEW

**Comment by MrMusic** [comment]
Thank you, the button is now displayed.

When testing with categories where the tester is the owner, the following did not work:
1. Edit
Authorization:
Edit = Denied
Edit own = Allowed
Error: Editing is not possible, the edit link is not displayed.

2. Delete
Authorization:
Delete = Denied
Delete own = Allowed
Error: The following error message appears when clicking on the delete button:
```
0 Class “Joomgallery\Component\Joomgallery\Administrator\Model\Log” not found

1 () JROOT\administrator\components\com_joomgallery\src\Model\CategoryModel.php:297
2 Joomgallery\Component\Joomgallery\Administrator\Model\CategoryModel->delete() JROOT\libraries\src\MVC\Controller\AdminController.php:143
3 Joomla\CMS\MVC\Controller\AdminController->delete() JROOT\libraries\src\MVC\Controller\BaseController.php:693 
```

**Comment by Elfangor93** [comment]
The reported error message will be fixed in PR #242 since it is not related to the topic in this PR.

**Comment by MrMusic** [comment]
Thank you very much, upload, edit and delete work as desired.
A (last) small problem has occurred:
For images and tags, the status of the first record in the list view cannot be changed by clicking on the icon (not even as superuser).
In addition, a PHP warning always appears in the list view:
Images:
`Warning: Undefined variable $canCheckin in ...administrator\components\com_joomgallery\tmpl\images\default.php on line 130`
Tags:
`Warning: Undefined variable $canCheckin in ...administrator\components\com_joomgallery\tmpl\tags\default.php on line 105`
This problem does not occur with categories.

DE:
Vielen Dank, Upload, Edit und Delete funktionieren wie gewünscht.
Ein (letztes) kleines Problem ist noch aufgetreten:
Bei Bildern und Tags lässt sich der Status des ersten Datensatzes in der list view durch klicken auf das Symbol nicht ändern (auch nicht als Superuser).
Außerdem erscheint immer eine PHP Warnung in der list view:
Bilder:
`Warning: Undefined variable $canCheckin in ...administrator\components\com_joomgallery\tmpl\images\default.php on line 130`
Tags:
`Warning: Undefined variable $canCheckin in ...administrator\components\com_joomgallery\tmpl\tags\default.php on line 105`
Bei Kategorien gibt es dieses Problem nicht.

**Comment by Elfangor93** [comment]
So hopefully this was now the last change for the ACL in the backend...

**Comment by MrMusic** [comment]
>So hopefully this was now the last change for the ACL in the backend.

Yeah, finally done!
I have tested this PR ✅ successfully.
Thank you very much.

**Pull request merged**
