### PR TITLE
Tags manager

### PR DESCRIPTION
**Pull request by Elfangor93**
## What is this pull request for

Basic functionality of Tags Manager realized. It is now possible to use all the buttons and functionalities of the Tags Manager.

## How to test this  pull request

- Click all the buttons, links and try everything out that is possible with the GUI inside the Tags Manager.

### CODE REVIEW

**Comment by eumel1602** [comment]
I installed the task manager on Windows 10 with J4.2.3. I couldn't see any error while playing around and trying.

maybe I understand it wrong?
Shouldn't I actually be able to assign a "tag" to a picture? But I can't find anything to enter.
After creating tags I can't do anything with them?

maybe someone can explain to me how and where I can use the tags??

**Comment by Elfangor93** [comment]
No assigning tags to images os not yet possible. This PR is just about creating, deleting, copying, ... of Tags inside the Tag manager.

**Comment by eumel1602** [comment]
> No assigning tags to images os not yet possible. This PR is just about creating, deleting, copying, ... of Tags inside the Tag manager.

Oh so ok ! So far I haven't been able to find any errors. it all worked for me

**Comment by szepty-ziemi** [comment]
Successfully tested on Linux. No Defects found.

The only discrepancy found is lack of informative popup in search field. This is how it looks in Joomla native tags:

obraz

Joomla native tags have columns selector. Do we plan to implement this in Tags Manager?

obraz

**Comment by szepty-ziemi** [comment]
I'm wondersing: Joomla has native tagging system com_tags. Why we develop separated tagging system for JoomGallery? Maybe there will be option to utilize Joomla core com_tags?

**Comment by eumel1602** [comment]
I've now tested the tag manager again with PHP 8.0.x (Windows) and I couldn't find any problems there either

**Comment by Elfangor93** [comment]
> I'm wondersing: Joomla has native tagging system com_tags. Why we develop separated tagging system for JoomGallery? Maybe there will be option to utilize Joomla core com_tags?

This Topic was discussed a lot before. The thing about com_tags is that it uses the UCM (unified content model) of Joomla core. The community does not like the UCM approach thats why I excpect com_tags to be deleted or replaced one day in the future.
I am quite sure that components using com_tags have to be modified afterwards.

I would like JoomGallery to be independent of this UCM shit. Thats why I decided to create our own tagging system like Phoca gallery does. I really much like Phocas tagging system. Its simple and easy for both developer and user.

**Comment by Elfangor93** [comment]
> Joomla native tags have columns selector. Do we plan to implement this in Tags Manager?

This is a new feature of Joomla 4.2.3. Columns selector is introduced not only for tags but for all kind of list views. This feature has not highest priority for me right now.

**Pull request merged**
