### PR TITLE
Fix upload/filesystem issues

### PR DESCRIPTION
**Pull request by Elfangor93**
This PR fixes some of the issues found in the area of
- upload process
- file management
- sanitisioning

Namely it solves issues #44, #53, #56, #68, #85

This PR was build on top of PR #83. With applying this PR we are much closer to the final single upload process.

### CODE REVIEW

**Comment by eumel1602** [comment]
can it be that this PR installation doesn't work?
bildschirmabgriff

**Comment by AlexanderSupp** [comment]
I have exactly the same error-message.

**Comment by Elfangor93** [comment]
The PR is still work in progress...

**Comment by Elfangor93** [comment]
PR is now ready to test...

**Comment by MrMusic** [comment]
Error when saving the configuration:
`Save failed with the following error: Incorrect integer value: 'none' for column ..._joomgallery_configs.jg_msg_upload_type at row 1`
It seems type 'tinyint(1)' is wrong.

**Comment by MrMusic** [comment]
One question about the path field in the categories database table:
The default entry "uncategorised" does not contain a leading slash.
Newly created categories have a leading slash "/".
Which is correct?

**Comment by reni68** [comment]
Tested issues #44 and #85 and both work:
#44: Categories in file system correct and images - old and new - in category Cat-B. 
         All thumbnails visible.

#85: "no image" thumbnail is displayed.

Tested on Linux with XAMPP, Joomla 4.2.9 and PHP 8.0.15.

**Comment by reni68** [comment]
> One question about the path field in the categories database table: The default entry "uncategorised" does not contain a leading slash. Newly created categories have a leading slash "/". Which is correct?

Global configuration can now be saved without error message.

**Comment by Elfangor93** [comment]
>The default entry "uncategorised" does not contain a leading slash.
Newly created categories have a leading slash "/".
Which is correct?

Without leading slash is correct. But a slash does not break functionality. But you pointed me towards some code which could make problems. I am working on it...

**Comment by eumel1602** [comment]
I tested problems #44 #53 #85 #83. Everything works for me now.

What I noticed about the topic: #56 / If I use an image or a category or a tag with only one or more spaces as a title, it saves it, but I can never edit the image again. Saving a e.g. Image with only one space should show an error from my point of view! / when I save a second image with one or more spaces, the system automatically adds a "(2)" and so it's clickable...

bildschirmabgriff

**Comment by Elfangor93** [comment]
@eumel1602 Can you please open an issue for your the titles issue?
I will not fix this here in this PR...

**Pull request merged**
