### PR TITLE
Code adjustments for Alpha 1 release

### PR DESCRIPTION
**Pull request by Elfangor93**
This PR prepars the code fot the first alpha release.
It adds a message that the component is still in development phase and intended for testing only.

Release date is set to be the 10.09.2023

### CODE REVIEW

**Comment by eumel1602** [comment]
Thank you for your working hours.
Notice line is displayed everywhere!
Apart from already known issues (e.g.: #91), I haven't found any errors at the moment. I'll test again during the week.

**Comment by reni68** [comment]
A menu for the JoomGallery brings me this error in the frontend:
grafik

Joomla 4.3.4 auf Linux und Xampp mit PHP-Version 8.1.17

**Comment by MrMusic** [comment]
The two warnings appears on Joomla pages not on the JoomGallery pages.

**Comment by reni68** [comment]
> The two warnings appears on Joomla pages not on the JoomGallery pages.

The messages appear when I create menu items from the JoomGallery menu types.

**Comment by AlexanderSupp** [comment]
> > The two warnings appears on Joomla pages not on the JoomGallery pages.
> 
> The messages appear when I create menu items from the JoomGallery menu types.

Try to change the PHP version to 8.0, may be this is the reason.

**Comment by reni68** [comment]
> Try to change the PHP version to 8.0, may be this is the reason.

php 8.0.x is only supported until 26.11.2023.
I now only have PHP 8.1.x in my test environment. :(

**Comment by Elfangor93** [comment]
@reni68 Thanks for reporting. Issue is fixed.

**Comment by MrMusic** [comment]
>Upload Multiple New is ok, but see debug information ??
grafik

@reni68 This Deprecated message already exists in the main branch.
I will create a separate pull request for it, as it has nothing to do with this pull request here.

**Pull request merged**
