### PR TITLE
Frontend cleanup and Infinte scroll

### PR DESCRIPTION
**Pull request by Elfangor93**
Combination of the two pull requests #217 (Frontend cleanup and category view) and #223 (Infinte scroll & load more).

It was requested to merge the two pull requests into one and rebase it towards the main branch to have the newest functionalities included.

### CODE REVIEW

**Comment by Elfangor93** [comment]
@reilldesign So I tried to merge our pull requests and rebase it to main. Can you please check, that the two template files `site/com_joomgallery/tmpl/category/default.php` and `site/com_joomgallery/tmpl/image/default.php` contain all your latest changes?

During rebase I had to accept incoming changes which I don't know I did correctly.

**Comment by reilldesign** [comment]
@Elfangor93 It looks good to me. Thank you very much.

**Comment by MrMusic** [comment]
1.Problem
Error when saving the Joomla and JoomGallery configuration:
```
0 Joomla\CMS\Event\Model\AfterCleanCacheEvent::onSetResult(): Argument #1 ($value) must be of type bool, array given, called in ...libraries\src\Event\AbstractEvent.php on line 227

# 	Function 	Location
1 	() 	JROOT\libraries\src\Event\Model\AfterCleanCacheEvent.php:107
2 	Joomla\CMS\Event\Model\AfterCleanCacheEvent->onSetResult() 	JROOT\libraries\src\Event\AbstractEvent.php:227
3 	Joomla\CMS\Event\AbstractEvent->setArgument() 	JROOT\plugins\system\joomgallery\src\Extension\Joomgallery.php:542
4 	Joomgallery\Plugin\System\Joomgallery\Extension\Joomgallery->setResult() 	JROOT\plugins\system\joomgallery\src\Extension\Joomgallery.php:203 
```

In addition, many warnings appear in the entire Joomla backend:
```
Warning: Undefined array key 0 in ...plugins\system\joomgallery\src\Extension\Joomgallery.php on line 218
Warning: Undefined array key 1 in ...plugins\system\joomgallery\src\Extension\Joomgallery.php on line 218
```

System: 
Joomla 5.1.0 with PHP 8.1
with Joomla 4.4.4 the problems does not occur.

2.Problem 
Sometimes the infinite scroll does not work: Not all images are displayed.

Demo with display of the same category and different number of columns: https://mrmusic63.de/jg4-dev/

Test:
3 columns: 12 images are displayed
4 columns: 16 images are displayed
5 columns: all 30 images are displayed
6 columns: all 30 images are displayed

DE:
1.Problem
Fehler beim speichern der Joomla und JoomGallery Konfiguration:
```
0 Joomla\CMS\Event\Model\AfterCleanCacheEvent::onSetResult(): Argument #1 ($value) must be of type bool, array given, called in ...libraries\src\Event\AbstractEvent.php on line 227

# 	Function 	Location
1 	() 	JROOT\libraries\src\Event\Model\AfterCleanCacheEvent.php:107
2 	Joomla\CMS\Event\Model\AfterCleanCacheEvent->onSetResult() 	JROOT\libraries\src\Event\AbstractEvent.php:227
3 	Joomla\CMS\Event\AbstractEvent->setArgument() 	JROOT\plugins\system\joomgallery\src\Extension\Joomgallery.php:542
4 	Joomgallery\Plugin\System\Joomgallery\Extension\Joomgallery->setResult() 	JROOT\plugins\system\joomgallery\src\Extension\Joomgallery.php:203 
```

außerdem erscheinen im gesamten Backend von Joomla viele Warnungen:
```
Warning: Undefined array key 0 in ...plugins\system\joomgallery\src\Extension\Joomgallery.php on line 218
Warning: Undefined array key 1 in ...plugins\system\joomgallery\src\Extension\Joomgallery.php on line 218
```

System: 
Joomla 5.1.0 mit PHP 8.1
mit Joomla 4.4.4 treten die Probleme nicht auf.

2.Problem
Manchmal funktioniert infinite scroll nicht: Es werden nicht alle Bilder angezeigt.

Demo mit Anzeige der gleichen Kategorie und unterschiedlicher Anzahl an Spalten: https://mrmusic63.de/jg4-dev/

Test:
3 Spalten: 12 Bilder werden angezeigt
4 Spalten: 16 Bilder werden angezeigt
5 Spalten: alle 30 Bilder werden angezeigt
6 Spalten: alle 30 Bilder werden angezeigt

**Comment by reilldesign** [comment]
@MrMusic The image titles in the Lightgallery display on your test page still link to the detailed view. I had corrected this error and deactivated it. Please install the complete pull request again for testing.

**Comment by MrMusic** [comment]
>The image titles in the Lightgallery display on your test page still link to the detailed view

I have now switched off the title. It makes no difference.

> I had corrected this error and deactivated it

Bug or feature? ;-)
For me it's a nice feature.

>Please install the complete pull request again for testing.

Hm, i have installed the lastet version from [Elfangor93:site-clean-infinity](https://github.com/Elfangor93/JG4-dev/tree/site-clean-infinity). No commits at Github since installation.

**Comment by reilldesign** [comment]
@MrMusic I have just reinstalled pull request #224. Infinite scroll and load more are working. Also the title is not linked. However, the menu parameters still need to be cleaned up and I also get this error when saving the menu setting and creating a new category  ( @Elfangor93 )

`0 Joomla\CMS\Event\Model\AfterCleanCacheEvent::onSetResult(): Argument #1 ($value) must be of type bool, array given, called in /mnt/web307/e1/94/5107694/htdocs/poollounge/libraries/src/Event/AbstractEvent.php on line 227`

**Comment by MrMusic** [comment]
@reilldesign Vielen Dank für deine Hilfe.

>Infinite scroll and load more are working

Ich habe nochmal den PR nochmal heruntergeladen und installiert, allerdings ohne Änderung.
Das Problem mit infinity scroll bleibt. Ich bin mir ziemlich sicher, dass das Problem mit den Bildgrößen und dem verfügbaren Platz zu tun hat.
Du kannst es hier nachvollziehen (Linux, Joomla 4.4.4, PHP 8.1):
https://mrmusic63.de/jg4-dev/index.php/test-3-spalten: Hier eine Kategorie mit 30 Bildern und max. verfügbarer Breite -> Es werden alle 30 Bilder angezeigt.
https://mrmusic63.de/jg4-dev/index.php/3-spalten-login-module: Die gleiche Kategorie, wenn der verfügbare Platz durch das Login-Modul eingeschränkt ist -> Es werden nur 12 von 30 Bildern angezeigt.

>and I also get this error when saving the menu setting and creating a new category

Das Problem tritt nur mit Joomla 5.1 auf und betrifft auch die anderen Branches.

>However, the menu parameters still need to be cleaned up

Ja, das betrifft generell alle globalen Parameter und die Vererbung. Das ist noch nicht fertig.

**Comment by Elfangor93** [comment]
>Error when saving the Joomla and JoomGallery configuration
In addition, many warnings appear in the entire Joomla backend

This errors will be fixed in PR #230

**Comment by reilldesign** [comment]
@MrMusic May i ask you once again to try the following combination

change in line 405
`loadImages = <?php echo $num_columns * 3; ?>;`

change in line 405
`rootMargin: '200px'`

change in line 418
`threshold: 0`

**Comment by MrMusic** [comment]
>change in line 405
rootMargin: '200px'

Do you mean line 417?
Thanks @reilldesign  I have applied your suggestions on the test page and it looks good for me.

**Comment by reilldesign** [comment]
@MrMusic thank you for testing and providing feedback. Yes, it must be line 417.

@Elfangor93 please accept the three changes, I have no authorization for this pull request

**Comment by Elfangor93** [comment]
@reilldesign Were these the correct adjustments?

**Comment by reilldesign** [comment]
@Elfangor93 fine - thanks

**Comment by MrMusic** [comment]
I have tested this PR ✅ successfully.
Thank you very much.

**Pull request merged**
