### PR TITLE
Fix issue: Image record saved if error during imagetype creation

### PR DESCRIPTION
**Pull request by Elfangor93**
This is a fix for issue #101 .

New image records will not get saved anymore if there was an error during image creation.

### CODE REVIEW

**Comment by Elfangor93** [comment]
> Whatever I do, Image Magick works and GD not. It shows me a blank screen.

@AlexanderSupp I am pretty sure this behavior is not related to the changes in this PR.

**Comment by rowi68** [comment]
I have tested this PR ✅ successfully.
After uploading new image with an error during image creation (too big size) it will not get saved anymore.

But i noticed that I got an error with a picture size of 6MB although the limit is set to 10 MB.

2024-01-20_14h01_22

2024-01-20_13h58_16

If I set the maximum size on 15MB, then picture will accepted.

**Comment by AlexanderSupp** [comment]
A second test performed from a scratch system.
Deinstalled JG. Checked DB-Tables, found xue7e_joomgallery_users_old_old_old, deleted this table.
Download JG4-dev-image-rollback at 20.01.2024 16:31
Installation OK.
Language German.
Upload without any changes of the defaults. Image size, 1402.86 KB / 1.33 MB, works correct.
Set max MB to 1
Upload same image, Error messages comes up, looks fine and is correct, because image too big.
Set max MB to 2
Upload same image, Error messages comes up, looks fine and is correct for me, because image size near a border.
Set max MB to 3.
Upload same image, No error messages, everything works fine.
Now I changed the parameter "Show warning" to "Yes, with hint". 
Max MB are still to 3.
Upload an image of 7 MB.
On a new, separate tab, the following occur:

Screenshot 2024-01-20 170617

I didn't remember exactly my parameters. I hope this test can reproduce the result from somebody.

**Comment by MrMusic** [comment]
I have tested this item ✅ successfully. Thank you very much.

**Comment by Elfangor93** [comment]
> But i noticed that I got an error with a picture size of 6MB although the limit is set to 10 MB.

Since we are using com_media's (Media Manager) filesystem plugins for the filesystem handling this error is coming from com_media and is not related to JoomGallery. Therefore this issue would need to be reported at the Joomla core.
https://github.com/joomla/joomla-cms

**Comment by Elfangor93** [comment]
> I didn't remember exactly my parameters of the first test. I hope this test can reproduce the result from somebody.

@AlexanderSupp I am pretty sure, this issue is more general and will not be solved within this PR. Please open a separate issue for that.

**Comment by rowi68** [comment]
> > But i noticed that I got an error with a picture size of 6MB although the limit is set to 10 MB.
> 
> @rowi68 Since we are using com_media's (Media Manager) filesystem plugins for the filesystem handling this error is coming from com_media and is not related to JoomGallery. Therefore this issue would need to be reported at the Joomla core. https://github.com/joomla/joomla-cms

I only noticed it and was not sure it would be interesting for you.  From my side it is not very important, because I usually never use pics of this size... :-)

**Comment by AlexanderSupp** [comment]
> I only noticed it and was not sure it would be interesting for you. From my side it is not very important, because I usually never use pics of this size... :-)

Yes, that is my understanding too.
I'm testing PR here and I don't actually have any problems with it.
And in doing so, I run into further issues that I can no longer even assess. How should I open an issue that I can't properly define in the title?

**Comment by MrMusic** [comment]
When creating an image, the wrong file size (default value from image.xml) is displayed, which is probably also causing confusion. Normally the value from com_media should be displayed here, analogue to the display in the configuration.
Otherwise I have not noticed any problems.

DE: Beim erstellen eines Bildes wird die falsche Dateigröße (Default-Wert aus der image.xml) angezeigt, vermutlich sorgt das auch für Verwirrung. Normalerweise sollte hier der Wert aus com_media stehen, analog zur Anzeige in der Konfiguration.
Ansonsten konnte ich keine Probleme feststellen.
new_image_filesize

**Pull request merged**
