### PR TITLE
New field: JG-Category selection

### PR DESCRIPTION
**Pull request by Elfangor93**
## What is this pull request for

It adds a new field to JoomGallery which allows to select a JoomGallery category using a modal box.
Clicking the button opens a modal box where you can search for the category. A click on the category name closes the modal and sets the category as new value in the field.
grafik

The field is used in the category edit form to select a parent category.

## How to test this  pull request

Go to category manager, edit a category and select a parent category. Use filter and sorting options in the provided modal box to search for the correct category in your gallery.

### CODE REVIEW

**Comment by Elfangor93** [comment]
Info for the testers:
grafik
In the modal box when you want to filter for a specific user, there is no dropdown to select available users. This is due to the fact that this dropdown field is added in another PR.
This is not a bug this is intended to be like that. As soon as this PR is merged the dropdown will be available.

**Comment by eumel1602** [comment]
I couldn't find any errors
  (J 4.2.5. / PHP 7.4 / Windows / Online test environment

**Comment by eumel1602** [comment]
It was not possible for me to sort the categories according to the number of pictures in the categories themselves!?

**Comment by Elfangor93** [comment]
Yes you are correct that is not possible. And I also will not implement that at that statge. We have to focus on the most important functions.

**Comment by MrMusic** [comment]
In category edit form if no parent category is selected, the term 'ROOT' should not appear. This may confuse some users.
Instead, a text like 'No parent category' or like in Joomla '- No parent -' should appear.

The same text should also appear in the (no category) button in the Popup.

**Comment by szepty-ziemi** [comment]
When trying to assign category to itself, we should have a bit more meaningful error message:

obraz

Eg. "You can't assign category to itself" or "You can't make child category of itself"

**Comment by Elfangor93** [comment]
> The same text should also appear in the (no category) button in the Popup.

No. The view in the popup will not only be used to select parent categories. Therefore I prefere having a button text which can be used everywhere in JoomGallery not only to select a partent category.

**Comment by Elfangor93** [comment]
> When trying to assign category to itself, we should have a bit more meaningful error message:

I dont want to override the error message since that would mean to override core classes which would blow up our code base unnecessarily. Instead I am planning to add a possibility to the field to exculde child categories in the list view (popup). That way users will not be able to select child categories and this error should not be raised anymore.

**Comment by Elfangor93** [comment]
@szepty-ziemi Do you like the solution to the error message issue?

**Comment by szepty-ziemi** [comment]
> @szepty-ziemi Do you like the solution to the error message issue?

That's a perfect solution :) Thank you.

obraz

**Pull request merged**
