### PR TITLE
Fix link to migration help page

### PR DESCRIPTION
**Pull request by MrMusic**

### CODE REVIEW

**Comment by Elfangor93** [comment]
Yes, if you want to host the english help articles in the other Joomla installation we can do that.
I was thinking of hosting both (english and german) articles in the main Joomla installation at https://www.joomgalleryfriends.net.
German within the manuitem `hilfe` and english within the manuitem with alias `help`.

**Comment by MrMusic** [comment]
So far, the german and english versions are separated into two installations. To avoid confusion, i would keep the separation.

**Comment by Elfangor93** [comment]
Maybe we can discuss this during the next meeting.

I would like to merge them into one multilangual Joomla in the near future, by the time we update it to Joomla 5 and JoomGallery 4.
Thats why I started this new article series already multilangal at the main website.

**Comment by MrMusic** [comment]
Everything is actually ready for the release of Alpha2.
Only these two PRs https://github.com/JoomGalleryfriends/JG4-dev/pull/199 and https://github.com/JoomGalleryfriends/JG4-dev/pull/200 still need to be merged.

**Review by Elfangor93 — APPROVED** [review]

**Pull request merged**
