### PR TITLE
Stable installation/update and deinstallation

### PR DESCRIPTION
**Pull request by Elfangor93**
Fixes the bug reported in issue https://github.com/JoomGalleryfriends/JG4-dev/issues/4

With this PR it is now possible to install the component on linux systems.

### CODE REVIEW

**Comment by Elfangor93** [comment]
### Tests to check install/update/uninstall
**Checks after Installation:**
- No errors during installation
- Default category created (Uncategorized)
- Default image types created (original, detail, thumbnail)
- Folder structure correctly created (/images/joomgallery/<imagetype>/uncategorized)
- Global configuation set created
- Ability to create and delete categories, images, configuration sets and image types

**Checks after Update** (installing the component again):
- No errors during update
- Ability to create and delete categories, images, configuration sets and image types

**Checks after Uninstallation:**
- No errors during uninstallation
- DB: joomgallery related tables deleted
- Table #__assets: all joomgallery related assets deleted
- Files and folders deleted (/images/joomgallery/)

### Testing everything with:
- Joomla 3.x / 4.x
- PHP 7.2.x / 7.3.x / 7.4.x / 8.0.x and 8.1.x
- MySQL 5.x / MySQL 8.x / MariaDB 10.x
- Apache / NginX
- Linux / Windows

### Mindest system voraussetzungen
- Joomla 4.0
- PHP 7.3.0
If the component is installed with a lower Joomla or PHP version, the installation should stop and and an error message will be shown.

**Comment by Elfangor93** [comment]
>MySQL 5.x / MySQL 8.x / MariaDB 10.x

@MrMusic Which database types do you think should be supported by Joomla 4.x?

**Comment by MrMusic** [comment]
I tried an installation on Joomla 4.1.2 and got the following error Installation error:
```
JoomGallery 4.x is only compatible to Joomla! 4.x
Error installing component
```
I think in script.php
`if(version_compare(JVERSION, '5.0.0', '<') || version_compare(JVERSION, '4.0.0', '>='))`
is wrong.

>@MrMusic Which database types & versions do you think should be supported by Joomla 4.x?

We should have the same system requirements as Joomla itself.
We should support MySQL 5.x and MySQL 8.x.
MariaDB is not 'officially' supported by Joomla - but there have been discussions about this for a long time.

**Comment by Elfangor93** [comment]
These are the system requirements for Joomla 4.x. I think, we should attach to these requirements and test our components in this systems:
https://downloads.joomla.org/technical-requirements
grafik

**Comment by szepty-ziemi** [comment]
Test Env:

PHP Built On: Linux s47.smarthost.pl 4.18.0-348.12.2.lve.el8.x86_64 #1 SMP Mon Jan 24 07:29:58 EST 2022 x86_64
Database Version: 10.3.34-MariaDB
PHP Version: 7.4.28
Web Server: Apache
Joomla! Version: Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0 

✓ No errors during installation
✓ Default category created (Uncategorized + Root)
✓ Default image types created (original, detail, thumbnail)
✓ Folder structure correctly created (/images/joomgallery/uncategorized)
✓ Global configuration set created

Ability to:

✓ create and delete categories,
✖create and delete images [ https://github.com/JoomGalleryfriends/JG4-dev/issues/13 ]
✓ create and delete configuration sets
? create and delete image types

**Comment by szepty-ziemi** [comment]
While trying to install on PHP 7.2.34

obraz

Installation is correctly stopped:

obraz

The only thing is error notification:

JoomGallery 4.x is only compatible to PHP versions greater than %s

The last part %s should display something meaningful. 

Error reported: https://github.com/JoomGalleryfriends/JG4-dev/issues/15

**Comment by szepty-ziemi** [comment]
Test Env:

PHP Built On Linux s47.smarthost.pl 4.18.0-348.12.2.lve.el8.x86_64 #1 SMP Mon Jan 24 07:29:58 EST 2022 x86_64
Database Version 10.3.34-MariaDB
PHP Version 8.0.16
Web Server Apache
Joomla! Version Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0 

✓ No errors during installation
✓ Default category created (Uncategorized + Root)
✓ Default image types created (original, detail, thumbnail)
✓ Folder structure correctly created (/images/joomgallery/uncategorized)
✓ Global configuration set created

Ability to:

✓ create and delete categories,
✓ create and delete images
✓ create and delete configuration sets
? create and delete image types

Checks after Update (installing the component again):

✓ No errors during update

Ability to:

✓ create and delete categories,
✓ create and delete images
✓ create and delete configuration sets
? create and delete image types

Checks after Uninstallation:

? No errors during uninstallation - Errors are mentioned, but no details provided, no stacks in Joomla. - the same issue as mentioned for PHP 7.4
✓ DB: joomgallery related tables deleted
✓ Table #__assets: all joomgallery related assets deleted
✓ Files and folders deleted (/images/joomgallery/)

**Comment by MrMusic** [comment]
Installation works now.

But problems already occur when creating new categories:
- No directories are created in the folder structure.
- In table #__joomgallery_catgories the 'path' is empty.

Testing environment with
Windows - XAMPP
Joomla 4.1.2
PHP 7.4.11
DB: 10.4.14-MariaDB
and 
Windows - XAMPP
Joomla 4.1.0
PHP 8.0.10
DB: 10.4.21-MariaDB

**Comment by szepty-ziemi** [comment]
I confirm that issue:

PHP Built On Linux s47.smarthost.pl 4.18.0-348.12.2.lve.el8.x86_64 https://github.com/JoomGalleryfriends/JG4-dev/pull/1 SMP Mon Jan 24 07:29:58 EST 2022 x86_64
Database Version 10.3.34-MariaDB
PHP Version 8.0.16
Web Server Apache
Joomla! Version Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

While creating categories - folders are not created.
Uploading image to selected category place file in ROOT folder on server.

**Comment by reilldesign** [comment]
I have successfully installed the version and created a test category. After the successful installation I wanted to install the language file as usual. but here there was an error message (see screenshot).

=============
System Information
=============
php: Linux localhost 3.10.0-1160.36.2.el7.x86_64 #1 SMP
dbserver: mysql
dbversion: 5.7.36-log
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.4.28
server: Apache/2.4.53 (Unix)
sapi_name: cgi-fcgi
version: Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:91.0) Gecko/20100101 Firefox/91.0



Bildschirmfoto am 2022-04-05 um 10 40 29

**Comment by szepty-ziemi** [comment]
I confirm this issue. Here is the stack: 
obraz

@reilldesign But I think that this part is just not developed yet ;)

**Comment by MrMusic** [comment]
>After the successful installation I wanted to install the language file as usual

There are currently no language files for JoomGallery 4.x to install. I think this is planned for a later date. First the 'basic' functions have to work.

**Comment by Elfangor93** [comment]
Installing a language file is not part of this Pull Request. During development there are just the english language files available which are installed during the default component installation.

**Comment by Elfangor93** [comment]
Did the rebase with the current main branch. Ready to merge.

**Comment by MrMusic** [comment]
The problem with the category path should be fixed in a separate PR, therefore only the installation/update/deinstallation shall be tested here.

I have tested this item ✅ successfully. Thank you very much.

**Pull request merged**
