### PR TITLE
fix ordering in list views

### PR DESCRIPTION
**Pull request by Elfangor93**
Fixes the bug that ordering was not possible in admin list views. Before this PR, selecting a different ordering in the list views did not affect the ordering of the items.

### CODE REVIEW

**Comment by szepty-ziemi** [comment]
Do I understand correctly: in this ticket we need to test if list ordering works wherever it is (Image Manager, Category Manager and Configuration Manager). 

So we need to create few rows and check if we're able to sort them by each column.

obraz

**Comment by Elfangor93** [comment]
Check, if the list views (images, categories, configurations, tags) are working as expected especially the ordering functionalities:
grafik

**Comment by szepty-ziemi** [comment]
Image Manager

X Access ascending
X Access descending
X Owner ascending (Is this who created image?) Doesn't seem to do anything
X Owner descending

✓ Ordering ascending
✓ Ordering descending
✓ Title ascending
✓ Title descending
✓ Status ascending
✓ Status descending
✓ Featured ascending
✓ Featured descending
✓ Approved ascending
✓ Approved descending
✓ Category ascending
✓ Category descending
✓ Author ascending
✓ Author descending
✓ Date ascending
✓ Date descending
✓ Hits ascending
✓ Hits descending
✓ Downloads ascending
✓ Downloads descending
✓ ID ascending
✓ ID descending

Test data:
obraz
obraz

**Comment by szepty-ziemi** [comment]
**Category Manager**

? Ordering ascending
? Ordering descending

 Categories do not have ordering column (also in DB) so I don't know which value is used to do the sorting... some thing is taken into account as sorting is done, but there is no visible reason for such a sorting.

X Author ascending
X Author descending

There is no Author value or column for category. This sorting doesn't do anything.

✓ Title ascending
✓ Title descending
✓ Parent category ascending
✓ Parent category descending
✓ Status ascending
✓ Status descending
✓ Access ascending
✓ Access descending
✓ Language ascending
✓ Language descending
✓ ID ascending
✓ ID descending

Test data:
obraz

**Comment by szepty-ziemi** [comment]
**Configuration Manager**

✓ User Group ascending (does order by name or privilege importance?)
✓ User Group descending

✓ Ordering ascending
✓ Ordering descending
✓ Title ascending
✓ Title descending
✓ Status ascending
✓ Status descending
✓ ID ascending
✓ ID descending

Test data:
obraz

**Comment by szepty-ziemi** [comment]
**Tags Manager**

✓ Access ascending
✓ Access descending

Sorting seems to be alphabetic? In Configuration Manager seems to be by importance?

✓ Ordering ascending
✓ Ordering descending
✓ Title ascending
✓ Title descending
✓ Status ascending
✓ Status descending
✓ Language ascending
✓ Language descending
✓ ID ascending
✓ ID descending

Test data
obraz

**Comment by MrMusic** [comment]
>Categories do not have ordering column (also in DB) so I don't know which value is used to do the sorting... some thing is taken into account as sorting is done, but there is no visible reason for such a sorting.

>There is no Author value or column for category. This sorting doesn't do anything.

Confirmed.

In JoomGallery 3.x it was this:

category ordering is the 'lft' column in database table
image ordering is the 'ordering' column in database table 

category owner is the 'owner' column in database table. There is no 'Author' field for categories, only for images.
image owner is the 'owner' column in database table 


In current JG4-dev:
The 'owner' field is missing in both database tables.

To avoid confusion the column 'Created by' should not be displayed in the admin views.

**Comment by szepty-ziemi** [comment]
System information: https://prnt.sc/bbLbOo40PPS7

**Image Manager**

X Access ascending
X Access descending

The same issue as under Linux: https://github.com/JoomGalleryfriends/JG4-dev/issues/19
There is additional filter above item list, and there could be set only one access type e.g "Public". Unless there will be a default filter value "All", sorting by Access has little sense.

X Owner ascending (Is this who created image?) Doesn't seem to do anything
X Owner descending

Issue the same as under Linux.

**All good:**

✓ Ordering ascending
✓ Ordering descending
✓ Title ascending
✓ Title descending
✓ Status ascending
✓ Status descending
✓ Featured ascending
✓ Featured descending
✓ Approved ascending
✓ Approved descending
✓ Category ascending
✓ Category descending
✓ Author ascending
✓ Author descending
✓ Date ascending
✓ Date descending
✓ Hits ascending
✓ Hits descending
✓ Downloads ascending
✓ Downloads descending
✓ ID ascending
✓ ID descending

Test data:
obraz

**Comment by szepty-ziemi** [comment]
@Elfangor93 great! Will test those changes and check remaining Category and Configuration Manager sorting.

**Comment by szepty-ziemi** [comment]
Fix for Image Manager CONFIRMED:

- Owner sorting removed
- Created by sorting ASC/ DESC works correctly

obraz

**Comment by szepty-ziemi** [comment]
System information: https://prnt.sc/bbLbOo40PPS7

ALL GOOD!

**Category Manager**

✓ Ordering ascending
✓ Ordering descending
✓ Created by ascending
✓ Created by descending
✓ Title ascending
✓ Title descending
✓ Parent category ascending
✓ Parent category descending
✓ Status ascending
✓ Status descending
✓ Access ascending
✓ Access descending
✓ Language ascending
✓ Language descending
✓ ID ascending
✓ ID descending

Test data:
obraz

**Comment by szepty-ziemi** [comment]
System information: https://prnt.sc/bbLbOo40PPS7

ALL GOOD!

**Configuration Manager**

✓ User Group ascending
✓ User Group descending
✓ Ordering ascending
✓ Ordering descending
✓ Title ascending
✓ Title descending
✓ Status ascending
✓ Status descending
✓ ID ascending
✓ ID descending

Test data:
obraz

**Comment by szepty-ziemi** [comment]
System information: https://prnt.sc/bbLbOo40PPS7

ALL GOOD!

**Tags Manager**

✓ Access ascending
✓ Access descending
✓ Ordering ascending
✓ Ordering descending
✓ Title ascending
✓ Title descending
✓ Status ascending
✓ Status descending
✓ Language ascending
✓ Language descending
✓ ID ascending
✓ ID descending

Test data:
obraz

**Pull request merged**
