### PR TITLE
add CategoryeditField

### PR DESCRIPTION
**Pull request by Elfangor93**
### What has been changed?
The category select field of the image and category form in the backend looks and behaves now the same as in com_content.

### CODE REVIEW

**Comment by szepty-ziemi** [comment]
**✓ VERIFIED**

FEATURE
Category selector in **category creation form**

GIVEN
Having more than one category already created
WHEN
Clicking on category selector 
THEN
List of categories are displayed
AND
User is able to select certain category

GIVEN
Having more than one category already created
WHEN
Clicking on category selector 
AND
Starting to type category name
THEN
Categories are filtered to match typed in name

Prerequisites:
obraz

TC1:
obraz
obraz
obraz

TC2
obraz

**Comment by szepty-ziemi** [comment]
**✓ VERIFIED**

FEATURE
Category selector in **image creation form**

GIVEN
Having more than one category already created
AND
Browsing to Backend -> JoomGallery -> Image Manager
AND
Clicking _New_ button
AND
Displaying new image creation form
WHEN
Clicking on category selector 
THEN
List of categories are displayed
AND
User is able to select certain category

GIVEN
Having more than one category already created
AND
Browsing to Backend -> JoomGallery -> Image Manager
AND
Clicking _New_ button
AND
Displaying new image creation form
WHEN
Clicking on category selector 
AND
Starting to type category name
THEN
Categories are filtered to match typed in name

Prerequisites:
obraz

T1
obraz
obraz

T2
obraz

**Comment by szepty-ziemi** [comment]
✓ VERIFIED

FEATURE
Category selector in category and image creation form - clearing selected category

GIVEN
Having more than one category already created
AND
Clicking _New_ button to create new category
AND
Clicking on category selector
AND
Choosing one of existing categories
WHEN
User click x in the right side of the field
THEN
Category selector field is cleared

GIVEN
Having more than one category already created
AND
Clicking _New_ button to create new image
AND
Clicking on category selector
AND
Choosing one of existing categories
WHEN
User click x in the right side of the field
THEN
Category selector field is cleared

T1
obraz
obraz

T2
obraz
obraz

**Comment by szepty-ziemi** [comment]
✓ VERIFIED

FEATURE
Category selector in category and image creation form - displaying categories that user is permitted to

GIVEN
Having more than one category already created, where at least one is with access set to group not available for current user
AND
Clicking New button to create new category
WHEN
Clicking on category selector
THEN
Only categories users is permitted to use, are displayed on the list

obraz
obraz
obraz
obraz

**Comment by szepty-ziemi** [comment]
✓ VERIFIED

FEATURE
Category selector in category and image creation form - currently edited category is not available to select

GIVEN
Having more than one category already created
WHEN
Clicking to edit one of the categories
THEN
In category selector, currently edited category is not available

obraz
obraz

**Comment by Elfangor93** [comment]
Rebased with main branch. Installation problem should be fixed now also in this branch.

**Pull request merged**
