### PR TITLE
Add support for webp images

### PR DESCRIPTION
**Pull request by MrMusic**
This pr adds the webp support as in JG 3.6.0
It is a redo from https://github.com/JoomGalleryfriends/JoomGallery/pull/102 for JG4.
With this it should be possible to upload webp images.

Additionally was fixed the wrong hint 'GD library not found' https://github.com/JoomGalleryfriends/JG4-dev/issues/61

### CODE REVIEW

**Review by Elfangor93 — COMMENTED** [review]
Code changes look good to me.

**Comment by szepty-ziemi** [comment]
It works well with GD, except animated webp. Uploading animated webp ends with 500 error.

With IM I get:

obraz

**Comment by MrMusic** [comment]
>Are animated webp supported anyway?

Sorry, currently not.

>With IM I get:

Do you use ImageMagick v6? Then you must also insert [this fix](https://github.com/JoomGalleryfriends/JG4-dev/pull/74/files#diff-e23bcfc7d5d6844350d45ad273785fe48b1fb6a2f6c94cc4feab4e9857862466) (line 934) in 'administrator/com_joomgallery/src/Service/IMGtools/IMtools.php' manually.

**Comment by Elfangor93** [comment]
@MrMusic could you update this PR based on main branch which now includes changes from PR #74. This way also IM could be tested for successful functionality.

**Comment by MrMusic** [comment]
@Elfangor93 : Done.

**Comment by Elfangor93** [comment]
Thank you very much for this feature!

**Pull request merged**
