### PR TITLE
Fix error in migration manager

### PR DESCRIPTION
**Pull request by Elfangor93**
In the migration manager the PHP error `Return value must be of type array` is thrown when trying to continue a migration. Additionally the ACL is done in the wrong way and also there an error is thrown.

This PR fixes this issues in the migration manager.

### CODE REVIEW

**Comment by MrMusic** [comment]
I have tested this PR ✅ successfully.
Thank you very much!

**Comment by reilldesign** [comment]
I get this error message

Step 2: Migration pre-check failed. Failed check: Source extension compatibility

I found the following thread on this topic
[https://www.forum.joomgalleryfriends.net/forum/index.php?thread/403-joomgallery-categories-root-gel%C3%B6scht/&postID=2271&highlight=Source%2Bextension%2Bcompatibility#post2271](url)

which xml file must be located where? Is there any other way to fix this error?

**Comment by reilldesign** [comment]
The J3 joomgallery_old.xml file was accidentally deleted due to the many de- and installations. After adding it manually, everything worked fine without an error message.


I have tested this PR ✅ successfully.
Thank you very much!

**Comment by rowi68** [comment]
I have also tested this PR ✅ successfully.

**Comment by Elfangor93** [comment]
Thank you all for testing!

**Pull request merged**
