### PR TITLE
Reset language file (Backend)

### PR DESCRIPTION
**Pull request by Elfangor93**
### New Naming logic
This pull request resets the language file for the backend and adds a new logic to the naming of the constants. The constants are now named based on its content rather than the location where its used.

Example JG3:
COM_JOOMGALLERY_CATMAN_HIDDEN="Hidden"

Example JG4:
COM_JOOMGALLERY_HIDDEN="Hidden"

### Usage of Core strings
Additionally the PR tries to use language constants from Joomla core whenever possible. This allows us to reduce the language strings to be maintained a lot.

Example JG3:
COM_JOOMGALLERY_COMMON_CATEGORY="Category"

Example JG4:
JCATEGORY="Category"

### Test instructions
You have to deinstall your currently installed JommGallery 4 version and reinstall it using this code. Otherwise the language files will mess up with previous installed versions!

- Switch through the backend GUI and look for untranslated strings. Report untranslated strings hre in the comment section of the PR
- Read through the english texts provided in the backend GUI. Report if you see any texts that does not make sense or are not good quality. Always provide your suggestion for your reported text.
- Untranslated strings in Config Manager>>General Settings>>Uploads>>Use image metadata>>Source Metadata Field will be threated in a different PR

### CODE REVIEW

**Comment by szepty-ziemi** [comment]
@Elfangor93 if this task is ready for testing, please, could you list acceptance criteria? Should we change if new naming of language constants and core Joomla ones are in use?

**Comment by eumel1602** [comment]
Hi !
I looked at all the descriptive texts in the BE. I could not find any mismatched texts on setting.
I cannot check whether the English grammar or the technical correctness is available. the translation of the texts in goggle brought me almost exclusively good German texts!

I noticed 4 things that I show here in four pictures and are framed in red!

1. Strange continuation of a new sentence with "," .. there are three or four other places where this is the case
2. something is going wrong here
3. should this string be translated over here or is the path correct here?
4. All three strings in the selection menu are not translated. Should that be so ?
bildschirmabgriff1

bildschirmabgriff2

bildschirmabgriff3

bildschirmabgriff4

**Comment by szepty-ziemi** [comment]
When creating NEW image and expanding text under Hidden settings, by clicking "more" there is ans language mistake:

There is:

but it will still be available through **direkt linking**

Should be:

but it will still be available through **direct linking**

obraz

**Comment by szepty-ziemi** [comment]
When creating NEW image, in Parameters tab, under Add Watermark? option, while expanding "more" text.

There is:

By default the watermark graphics file is located in 'media/joomgallery/images/' with the file name watermark.png. You can change both path and file name but you will also have to adjust the path and filename in General Settings » Paths, Directories, Files and Formats accordingly. 

Should be:

By default the watermark image file is located in 'images/joomgallery/' with the file name watermark.png. You can change both path and file name, but you will also have to adjust the path and filename in General Settings » Image Processing » Watermark accordingly. 

obraz

**Comment by szepty-ziemi** [comment]
When creating NEW image, in Parameters tab, under Show Exif data? option, while expanding "more" text.

There is:

If "Yes" by the following options you can decide which information will be published. Otherwise they are ineffective. 

Should be:

The following options allow you to decide if Exif data information will be published. Otherwise they are hidden. 

obraz

**Comment by szepty-ziemi** [comment]
When creating NEW image, in Parameters tab, under Show Exif data? option, while expanding "more" text.

There is:

If "Yes" by the following options you can decide which information will be published. Otherwise they are ineffective. 

Should be:

The following options allow you to decide if IPTC data information will be published. Otherwise they will be hidden.

obraz

**Comment by szepty-ziemi** [comment]
In Image Manager when there is at least one image created. Hove over icon in Approved column - untranslated language constant:

obraz

**Comment by szepty-ziemi** [comment]
When in Image Manager, click Options button in upper right corner - untranslated language constants:

COM_JOOMGALLERY_ADMENU_EXTENDED_CONFIG_LABEL
COM_JOOMGALLERY_ADMENU_EXTENDED_CONFIG_DESC

obraz

**Comment by szepty-ziemi** [comment]
In Category Manager when creating/editing category, under Password option:

There is:

With that, the category will only be accessible for the users in frontend if they enter the correct password. Please note that restricting access via access levels is stronger which means that users cannot access categories with too high access level even if they know the respective password. 

Should be:

This feature will allow to access the category after providing correct password. Please note, that restricting access via access levels is more secure, as users cannot access categories with too high access level, even if they know the respective password. 

obraz

**Comment by eumel1602** [comment]
In Image Manager when there is at least one image created. If I go over the image title, one comes up  untranslated language constant!
Screenshot 2022-09-08 171054

**Comment by szepty-ziemi** [comment]
In Image Manager with at leas one image created, hover over category name - untranslated constant:

COM_JOOMGALLERY_EDIT_CATEGORY

obraz

**Comment by szepty-ziemi** [comment]
In Category Manager when creating/editing category, under Exclude from toplists option:

There is:

With enabling this option you can exclude this item from the search. More...
Please note that this option is not automatically passed on to sub-categories. Of course, enabling this option could create confusion at the visitors of your site because some images won't appear in the search results even if they type in correct keywords. 

Should be:

By enabling this option this item will be excluded from the search. More...
Please note that this option is not automatically passed on to sub-categories. Enabling this option could create confusion, as  image won't appear in the search results, even if user type in correct search query. 

obraz

**Comment by szepty-ziemi** [comment]
In Category Manager when creating/editing category, under Thumbnail option:

There is:

Here you may select an image which is set as the thumbnail of this item. 

Should be:

Here you may select an image, which will be set as category thumbnail. 

obraz

**Comment by szepty-ziemi** [comment]
I suggest to follow general Joomla rules to display alias field and it description:

We have:

obraz

Joomla article have:

obraz

There is no additional description for this field, instead we have a placeholder inside field.

**Comment by szepty-ziemi** [comment]
In Category Manager when creating/editing category, in Parameters tab, under Offer Downloads:

There is:

This can overwrite the setting in tab 'User Access Rights->Download->Offer Downloads' in JoomGallery Configuration Manager 

Should be:

This will overwrite the setting in User settings » Downloads in JoomGallery Configuration Manager.

obraz

**Comment by szepty-ziemi** [comment]
In Category Manager when creating/editing category, in Parameters tab, under Allow Comments:

We do not have comments settings in User settings in Joomgallery Configuration Manager. If it will be developed later, we need to fix mentioned settings path anyway.

obraz

**Comment by szepty-ziemi** [comment]
In Category Manager when creating/editing category, in Parameters tab, under Allow Rating:

There is:

This can overwrite the setting in tab 'User Access Rights->Ratings->Allow Rating' in JoomGallery Configuration Manager 

Should be:

This will overwrite the setting in User settings » Ratings in JoomGallery Configuration Manager.

obraz

**Comment by szepty-ziemi** [comment]
In Category Manger, in Permission tab:

- untranslated constant JTOOLBAR_UPLOAD_INOWN 

obraz

- in tootips redundant tag <strong> is used (apply to all options)

obraz

- untranslated constant in tooltip - COM_JOOMGALLERY_ACTION_IMAGE_DELETE_OWN_DESC                                        

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> General Settings (BTW maybe we should rename one of the General settings as this looks weird having the same names one under another :) Maybe we could use Common Settings?) -> Real paths

There is:

Please note that the hit counter won't work anymore then if you don't use the default detail view. Additionally the image files cannot be protected anymore against unauthorised access (protection would be possible via htaccess, for example).
This option gets overridden for detail and original images by enabling the watermark in tab 'Detail View' -> 'General Settings' and for thumbnails by enabling dynamic cropping in tab 'Frontend Settings' -> 'General Settings' as well as by using absolute paths for each of the image sizes. 

Should be:

Please note, that the hit counter won't work with this setting enabled. Additionally the image files won't be protected against unauthorised access (protection would be still possible e.g via htaccess). Enabling watermark in General Settings » Image processing » Watermark in JoomGallery Configuration Manager will override this setting for detail and original images. Also enabling dynamic cropping for thumbnails in General Settings » Image processing » Image processing
(static images) » Show settings »  Resizing for thumbnails, and using absolute paths for each of the image sizes, will also override this setting. 

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> General Settings -> Check for updates?

There is:

Do you want the gallery to check automatically for available updates of itself and its extensions? More...
For this the gallery reads an [RSS feed](https://www.en.joomgalleryfriends.net/components/com_newversion/rss/extensions.rss) provided on joomgalleryfriends.net.

Should be:

Do you want the gallery to check automatically for component and extension updates? More...
Checking for updates gallery reads an [RSS feed](https://www.en.joomgalleryfriends.net/components/com_newversion/rss/extensions.rss) provided at joomgalleryfriends.net.

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> Uploads -> Show warning - untranslated string:

COM_JOOMGALLERY_CONFIG_GS_TAB_BACKEND_REPLACE_OPTION_2_SHOWWARNING

obraz

There is:

Shows a warning during upload, if one of the above selected metadata is not present in the image. More...
This setting applies regardless of the debug setting in the upload form.
_With hint: In addition to the warnings a hint will show the user a solution to the problem._ 

I'm not sure about the last sentence... should it be altered eg. A hint with possible solution will be displayed along with the warning.

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> Image Processing -> Image processor

There is:

Choose the tool used for image processing. More...
The tool should already be installed on the server and is required for manipulating images such as resizing or adding a watermark to them. Most servers run a PHP version that already has the GD2 implemented. The GD version installed on your system is displayed in the line above this paragraph. If only the GD-Software is present you should always prefer GD2 because otherwise you will miss several manipulating functions. If ImageMagick is installed you should always prefer that software, because the results will be much more better. 

In my system select displays "GD Library" without any version. Maybe this description should be altered? Eg:

Choose the tool used for image processing. More...
The tool should already be installed on the server and is required for manipulating images such as resizing or adding a watermark to them. Most servers run a PHP version that already has the GD Library implemented. If your server has more than one GD versions available you should always prefer GD2, otherwise you will miss several manipulating functions. If your server has ImageMagick available then we recommend to use this library as image transforming results will be much better. 

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> Image Processing -> Watermark

There is:

Path to where the watermark is saved. In this path/folder the image for generating the watermark is saved. You need to specify a path here even if you do not activate the watermark function. 

Should be:

Path to watermark file, located on your server. Path needs to be specified, even if you don't use watermark feature. 

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> Image Processing - > Image processing -> Show Settings

There is:

Resizing images? If you enable the resizing all uploaded images will be resized to the maximum dimensions you have specified (one setting below this one). More...
Those downsized images will be be used for display in the detail view. To prevent bursting the template it is good advice to enable this feature and to specify values that suit the template. If the feature remains disabled the images will be displayed in the size they have been uploaded. The resizing applies to the detail view only. The images used for the popup remain untouched and are displayed in their original upload size. If you want to affect the size of the popup you need to do that before you upload the images. 

Should be:

Resizing images? If you enable image resizing, all uploaded images will be resized to the maximum dimensions you have specified (one setting below this one). More...
Resized images will be be used for display in the detail view. It's advised to use image resizing to avoid issues with layout display. If the feature remains disabled, the images will be displayed in the size they have been uploaded. The resizing applies to the detail view only. The images used for the popup, remain untouched and are displayed in their original upload size. If you want to affect the size of the popup, you need to do that before you upload the images. 

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Recipients for the upload messages

There is:

Whom do you want to send messages about new images? If you select '- Default Recipients -' here and if sending messages is enabled above all users who have set 'Receive System E-mails' to 'Yes' will get a message. 

Should be:

Whom do you want to send messages about new images? If you select '- Default Recipients -' here and if sending messages is enabled above, all users who have set 'Receive System E-mails' to 'Yes' in Joomla user settings, will receive a notification message. 

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Recipients for the download messages

There is:

Whom do you want to send messages about image downloads? If you select '- Default Recipients -' here and if sending messages is enabled above all users who have set 'Receive System E-mails' to 'Yes' will get a message. 

Should be:

Whom do you want to send messages about image downloads? If you select '- Default Recipients -' here and if sending messages is enabled above, all users who have set 'Receive System E-mails' to 'Yes' in Joomla user settings, will receive a notification message. 

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Recipients for the comments messages

There is:

Whom do you want to send messages about new comments? This message will only be sent if it is necessary to approve the comments.
If you select '- Default Recipients -' here and if sending messages is enabled above all users who have set 'Receive System E-mails' to 'Yes' will get a message.
You may select '- No User -' here, if you only want to send messages to the image owners. Please check the option below for that. 

Should be:

Whom do you want to send messages about new comments? This message will be sent only if comment approval will be required. If you select '- Default Recipients -' here and if sending messages is enabled above, all users who have set 'Receive System E-mails' to 'Yes' in Joomla user settings, will receive a notification message. If you want to send messages to the image owners only, please select '- No User -' and check the option below to 'Yes'. 

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Message for image owner

There is:

If this option is enabled the user who ownes the image which is commented will receive a message, too. This message will also be sent if it is not necessary to approve the comments. If they have to be approved the message won't be sent until this is done.

Should be:

If this option is enabled, user who owns commented image will also receive a notification message. Message will be sent also if comment approval is not required. If they have to be approved, the message won't be sent until this is done

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Sending method for the image claims

There is:

On which way do you want to send messages about claims? This option has to be enabled for using the button for image claims. 

Should be:

On which way do you want to send messages about claims? This option has to be enabled in order to activate image claims button. 

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Recipients for the image claims

There is:

Whom do you want to send the image claims? If you select '- Default Recipients -' here and if sending messages is enabled above and in category or detail view all users who have set 'Receive System E-mails' to 'Yes' will get a message. 

There should be:

Whom do you want to send messages about image claims? If you select '- Default Recipients -' here and if sending messages is enabled above in category or detail view, all users who have set 'Receive System E-mails' to 'Yes' in Joomla user settings, will receive a notification message. 

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Message for image owner (reports)

There is:

If this option is enabled the user who ownes the image which somebody complains about will receive a message, too. 

Should be:

If this option is enabled, user who owns reported image will also receive a notification message.

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Sending method of image rejection messages

There is:

On which way do you want to send messages about reasons for rejecting images? A message will only be send if you fill the respective field while rejecting an image in image manager. 

Should be:

On which way do you want to send messages about image rejection reason? Message will be send only, if you fill the respective field while rejecting an image in Image Manager. 

obraz

Configuration Manager -> General Settings -> Image Processing - > Image processing -> Messages -> Recipients for the upload messages

There is:

Whom do you want to send messages about new images? If you select '- Default Recipients -' here and if sending messages is enabled above all users who have set 'Receive System E-mails' to 'Yes' will get a message. 

Should be:

Whom do you want to send messages about new images? If you select '- Default Recipients -' here and if sending messages is enabled above, all users who have set 'Receive System E-mails' to 'Yes' in Joomla user settings, will receive a notification message. 

obraz

**Comment by szepty-ziemi** [comment]
General in Configuration Manager:

There is:

User group for which this settings are applied for 

Should be:

User group to which this settings apply to.

Settings apply **to** someone... users may apply **for** something.

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> General Settings -> User Settings - > Enable userspace

There is:

The userspace is the administration panel for the frontend. More...
It is the place - depending on the following settings - where users can upload, delete or edit images and create or delete categories. The uploaded images are displayed in table view. In case more than one category is permitted for user upload the user can also move images to an other category.
Please select whether a user is allowed to upload images or create categories.
If not, the following options and the settings in Frontend Settings » User Panel will be ignored.	

Should be:

The userspace is frontend user administration panel. More...
In Userspace - depending on the settings available below - users can upload, delete or edit images and create or delete categories. The uploaded images are displayed in table view. If user is permitted to upload to more than one category, user can also move images between categories. Please select, whether user is allowed to upload images or create categories.
If not, the following options and the settings in Frontend Settings » User Panel will be ignored.

Last sentence needs to be verified for configuration path. Does it mea setting in current "Frontend Views"?

obraz

Configuration Manager -> General Settings -> User Settings - > Admin approval

There is:

Images uploaded in the frontend need to be approved by an administrator before they are displayed in the frontend (Yes). Otherwise they will be approved automatically and published to the frontend right away (No). 

Should be:

If set to "Yes" images uploaded in the frontend, need to be approved before publication by an administrator. Otherwise they will be approved and published automatically on the frontend. 

obraz


Configuration Manager -> General Settings -> User Settings - > Max. User-Categories

There is:

How many categories is each user allowed to create in the frontend? 

Should be:

How many categories frontend user is allowed to create?

obraz

Configuration Manager -> General Settings -> User Settings - > Max. User-Images

There is:

How many images is each user allowed to upload in the frontend? More...
Once the maximum number is reached the user will be notified and the upload will be cancelled.

Should be:

How many images frontend user is allowed to upload? More...
Once the maximum number is reached, the user will be notified and the upload will be suspended.

obraz

Configuration Manager -> General Settings -> User Settings - > Timespan in days

There is:

You may define a period of time in days in which the maximum number of images can be uploaded. More...
If the value for this parameter is 0, then the previous parameter has to be seen as an absolute limit. 

There should be:

I'm not sure here, whet description is trying to say. It means number of days in which max image upload could take place? So let's say it's 2 days (and max upload is 500). Does it mean that I may upload 500 within 2 days... each next 2 days? So after those two days passed I'm allowed to upload 500 images more within next 2 days?

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> User Settings -> Upload -> Display copyright notice

There is:

Do you want to display a copyright notice in the upload form? More...
It will inform the user on the fact that uploaded images need to be free of third party rights. The wording can be customised by editing the frontend constant COM_JOOMGALLERY_UPLOAD_NEW_IMAGE_COPYRIGHT .
NOTE!! The copyright text deposited under the afore mentioned constant is only meant as sample. It does not lay a claim on legal security. In each individual case a legal advice should be consulted for the formulation of the text!

Should be:

Do you want to display a copyright notice in the upload form? More...
It will inform the user on the fact that uploaded images need to be free of third party rights. The notice content can be customized by editing the frontend constant COM_JOOMGALLERY_UPLOAD_NEW_IMAGE_COPYRIGHT.
NOTE!! The default copyright notice in mentioned constant is only an example. In each individual case a legal advice should be consulted for the notice preparation!

obraz

Configuration Manager -> User Settings -> Upload -> Default upload category

There is:

You may select a user's default upload category that means whether the category field of the upload form is filled with a default value. More...
You may select between the oldest and newest category created by the user himself (Oldest from own, Newest from own) and the oldest and newest category from all available categories the user has upload access to. If you select 'None' the category field in the upload form will be empty.

This option is only effective if the option General Settings » Additional Functions » Disable unrequired checks is not activated!	

Should be:

You may select a default user upload category. Category field of the upload form will be filled with default value set here. More...
You may select between the oldest and newest category created by the user himself (Oldest from own, Newest from own) aor the oldest and newest category from all available categories the user has upload access to. If you select 'None' the category field in the upload form will be empty by default.

Note: last sentence point to non existing place in current form. Should it be removed or rather updated?

obraz

Configuration Manager -> User Settings -> Upload -> Offer option 'Problematic Image Files'

There is:

Do you want to offer an upload without resize? More...
Depending on your server configuration, errors may occur during upload for some images. These errors may be caused by several reasons (not enough memory, missing libraries, bugs in the code, misconfigurations,...). With this option a way is offered to the user to upload problematic images anyway. This means that they would not get resized even if the resizing feature is turned on and they would therefore be displayed in their full original size in detail view. A selection box with additional explanation is displayed to the user in the frontend. 

Should be:

Do you want to allow for upload without resize? More...
Depending on your server configuration, during upload errors may occur for some images. These errors may be caused by several reasons (not enough memory, missing libraries, bugs in the code, misconfigurations etc.). This option allows user to upload such a problematic images. They will be not resized, even if the resizing option is enabled. They will be displayed in their full original size in detail view. A selection box with additional explanation in the frontend. 

obraz

Configuration Manager -> User Settings -> Upload -> Display upload quota

There is:

Do you want to display a notice that informs the user on the maximum size and the maximum number of uploaded images? 

Should be:

Do you want to display a notice about maximum upload size and image quantity? 

obraz

Configuration Manager -> User Settings -> Upload -> Redirect after upload

There is:

Do you want to redirect frontend user after successful image upload? More...
If enabled, user will be redirected selected page. All upload and debug information will be displayed there. In other case, user will stay on upload page, upload and debug information will be displayed in the form, along with links to go back to user panel.

**Comment by szepty-ziemi** [comment]
Configuration Manager -> User Settings -> Downloads -> Offer Downloads

There is:

Do you want to offer downloads via the download button in the different views? More...
Please check the options for these ones in the corresponding tabs of the configuration manager. 

Should be:

Do you want to offer downloads by displaying download button in the different views? More...
Enabling this will display additional download options below.

obraz

Configuration Manager -> User Settings -> Downloads -> Advice if of not enough rights

There is:

Should users without enough rights be given a hint that downloading images is possible with more permissions? 

Should be:

If enabled, it will display a hint for users without enough rights, that downloading images is possible only with appropriate permissions.

obraz

Configuration Manager -> User Settings -> Downloads -> Download Images

Untranslated constant ware already reported by @eumel1602 They are ass follows:

COM_JOOMGALLERY_CONFIG_UR_UD_DETAIL_IFNO_ORIGINAL
COM_JOOMGALLERY_CONFIG_UR_UD_DETAIL_ONLY
COM_JOOMGALLERY_CONFIG_UR_UD_ORIGINAL_ONLY

There is:

Which image do you want to make available for download? "Detail Images Only" will choose the images as displayed in detail view. "Originals Only" will choose the original images as displayed in the popup (provided that it is still present). Of course this setting only works in case you made the download itself available. 

Should be:

Which image do you want to make available for download? "Detail Images Only" will allow to download detail view image. "Originals Only" will allow to download original image, as displayed in the popup. This settings work only when Offer Downloads is enabled.

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> User Settings -> Ratings -> Allow Rating

There is:

This option displays a rating field in the detail view of the gallery and allows users to rate images. More...
The range can be specified in the following setting. 

Should be:

Do you want to offer image rating by displaying rating field in the detail view? More...
Enabling this, will display additional rating options below.

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> User Settings -> Reports -> Allow sending claims

There is:

This option has to be enabled if you want to allow your users to send claims (report) for images in the gallery. More...
Please note that additionally the corresponding options for that in tab 'General Settings' -> 'Messages' have to enabled, too.
Since the button for creating a report has to be shown at least in view please check also the options for display the buttons in the different views in the corresponding tabs of the configuration manager. 

Should be:

Enable if you want to allow your users to send claims (report) for images in the gallery. More...
Please note, that option in  General Settings » Messages Sending method for the image claims » have to set different than None.

I don't understand what last sentence is trying to say as it doesn't point to any setting in particular.

obraz

Configuration Manager -> User Settings -> Reports -> Advice if of not enough rights

There is:

Should users without enough rights be given a hint that reporting is possible with more permissions? 

Should be:

If enabled, it will display a hint for users without enough rights, that reporting images is possible only with appropriate permissions.

obraz

**Comment by szepty-ziemi** [comment]
@Elfangor93 i tested all available screens and gave my suggestions to existing translations. They are regarding meaning, punctuation, settings path correction, form and typos.

@eumel1602 on image 3 there is not an issue as we mention there a language constant literally. This constant could be use to override and add own legal rights notice.

**Comment by eumel1602** [comment]
> @eumel1602 on image 3 there is not an issue as we mention there a language constant literally. This constant could be use to override and add own legal rights notice.

OK everything good! Thank you for the information

**Comment by Elfangor93** [comment]
@szepty-ziemi and @eumel1602 . Thank you for testing. I addressed all your comments concerning missing language strings. Changing the content of texts will be addressed in a different PR. Where this comments will still be considered and changed. But this way I can start working on the Tags & Configuration Manager in parallel.

**Comment by Elfangor93** [comment]
@MrMusic could you please take over the missing steps (changing the content of texts) in a new PR?

**Comment by MrMusic** [comment]
>@MrMusic could you please take over the missing steps (changing the content of texts) in a new PR?

@Elfangor93 Agreed.

I will create a new PR for the remaining reported comments.

Many thanks to @Elfangor93, @szepty-ziemi and @eumel1602 !

**Comment by MrMusic** [comment]
@szepty-ziemi Thank you very much!

Here my answers to your hints and questions:

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241044270
The texts in these subforms apply equally to all image types. therefore, they must be formulated in such a way that they are suitable for all image types.

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1240801332
>This part doesn't make sens in image manager (By hiding categories it is possible to create separate areas in the gallery, for example. For that please create a menu item for the hidden categories.) So I'm suggesting to remove it.

Currently there is only one language constant for 'hidden categories' and 'hidden images'. Therefore, identical descriptions appear in both places. If different descriptions should be appear, another language constant must be introduced. Needs discussion.
@Elfangor93 What do you mean?

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1240951604
>Configuration Manager -> General Settings -> General Settings (BTW maybe we should rename one of the General settings as this looks weird having the same names one under another :) Maybe we could use Common Settings?) -> Real paths

I agree with this, but we need a new constant for this. 
@Elfangor93 What do you mean?

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1240968531
>I'm not sure about the last sentence... should it be altered eg. A hint with possible solution will be displayed along with the warning.

I think this setting should have three options, not only on/off.
@Elfangor93 Can you check if this field should have type="list"?

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241103458
>Recipients for the upload messages... (duplicated occured)

I think here is a wrong language constant used for field jg_msg_global_from.
@Elfangor93 please check the language constants in config.xml line 345 and 346

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241107590
>Settings apply to someone... users may apply for something.

Should this sentence also be included? i did not quite understand this.

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241107590
>I don't understand what this description is trying to say. I think that description for Title field is not necessary. We don't use it in Image and Category Manager. But if we want to use it... the maybe it should say " Configuration set title"?

I suspect the text should not appear here.
@Elfangor93 can you check if JGLOBAL_FIELD_FIELD_ORDERING_DESC is right here or can it be deleted?

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241841194
>Last sentence needs to be verified for configuration path. Does it mea setting in current "Frontend Views"?

Since there is no frontend user panel yet, this may have to be changed later.

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241841194
>I'm not sure here, whet description is trying to say. It means number of days in which max image upload could take place? So let's say it's 2 days (and max upload is 500). Does it mean that I may upload 500 within 2 days... each next 2 days? So after those two days passed I'm allowed to upload 500 images more within next 2 days?

Yes you are right :-)

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241926719
>Note: last sentence point to non existing place in current form. Should it be removed or rather updated?

It is unclear whether this function will still exist in this form in the future. This may have to be changed later.

https://github.com/JoomGalleryfriends/JG4-dev/pull/34#issuecomment-1241960396
>I don't understand what last sentence is trying to say as it doesn't point to any setting in particular

For different views such as category, toplists, search, etc., there was a separate setting for displaying or not displaying the button.
Currently, these settings do not (yet) exist. This may have to be changed later.

**Comment by szepty-ziemi** [comment]
> Settings apply to someone... users may apply for something.
> Should this sentence also be included? i did not quite understand this.

@MrMusic no, no, This part is just a grammar explanation :)

**Comment by Elfangor93** [comment]
> Currently there is only one language constant for 'hidden categories' and 'hidden images'. Therefore, identical descriptions appear in both places. If different descriptions should be appear, another language constant must be introduced. Needs discussion.
@Elfangor93 What do you mean?

I did this by purpose to save translations. But we can do two different constants if you prefer that...

**Comment by Elfangor93** [comment]
> 

    Configuration Manager -> General Settings -> General Settings (BTW maybe we should rename one of the General settings as this looks weird having the same names one under another :) Maybe we could use Common Settings?) -> Real paths
I agree with this, but we need a new constant for this.
@Elfangor93 What do you mean?

Agree

**Comment by Elfangor93** [comment]
> I'm not sure about the last sentence... should it be altered eg. A hint with possible solution will be displayed along with the warning.
I think this setting should have three options, not only on/off.
@Elfangor93 Can you check if this field should have type="list"?

Yes in JG3.x we had three options. I think it makes sense to have three options again

**Comment by Elfangor93** [comment]
> I don't understand what this description is trying to say. I think that description for Title field is not necessary. We don't use it in Image and Category Manager. But if we want to use it... the maybe it should say " Configuration set title"?
I suspect the text should not appear here.
@Elfangor93 can you check if JGLOBAL_FIELD_FIELD_ORDERING_DESC is right here or can it be deleted?

Can be deleted...

**Comment by Elfangor93** [comment]
> Recipients for the upload messages... (duplicated occured)
I think here is a wrong language constant used for field jg_msg_global_from.
@Elfangor93 please check the language constants in config.xml line 345 and 346

Sorry I dont get it. What is the probelm here?

**Comment by MrMusic** [comment]
> I did this by purpose to save translations. But we can do two different constants if you prefer that...

I would be in favour of using different constants here to provide the user with the most accurate descriptions possible. 
I will change it.

**Pull request merged**
