### PR TITLE
Remove ACL for images

### PR DESCRIPTION
**Pull request by Elfangor93**
This PR fixes the problem reported in issue #252.

With this PR applied, there is no Permissions tab anymore in the image form view. Instead there are two tabs in the category form view. One for permissions regarding the category itself and one regarding all images within this category.

grafik

# Testing instructions
**You need to install a new, fresh JoomGallery in order for this PR to work!**

Instead of having permissions for each image, we have now permissions for all images within one category.
Create different users and apply different usergroups to them. Log in with this user and check if the permissions are applied correctly according to the permissions you set in the configuration for this usergroup.

**Attention!**
Forntend forms may not work correctly and throw errors. This is most probably due to the fact that the forms itself are not yet correctly set up (missing form fields, wrong URLs, wrong variables) in their corresponding template. Fixing these templates will not be part of this PR.

Following permissions should be tested at least:

## Category
- Create / Own
- Delete / Own
- Edit / Own
- Edit State

## Image
- Upload / Own
- Delete / Own
- Edit / Own
- Edit State

### CODE REVIEW

**Comment by rowi68** [comment]
After the installation of this PR nothing works on the page anymore.
Error message:
2024-09-15_15h23_45

J5.1.4 | PHP 8.2

**Comment by Elfangor93** [comment]
Where does this error happens?
Can you provide a call stack?

**Comment by rowi68** [comment]
This error came directly after the installation of the PR and now nothing can be operated in the backend (also frontend)
call stack : 
2024-09-15_18h37_31

**Comment by rowi68** [comment]
I tried reproduce again with J4.4.8
First error message just after PR installation was:
2024-09-15_20h55_40

Then, after clicking any button in BE Menu appears:
2024-09-15_21h03_59

Sorry, no call stack of first message at the moment because debugging mode was off...

**Comment by Elfangor93** [comment]
@rowi68 This looks to me like a problem with the namespacing lookup in the Joomla! Core. Please try to delete the file `autoload_psr4.php` in `/administrator/cache` and then refresh the page.
This way the PSR4 path cache is recreated and hopefully Joomla finds afterwards the JoomGallery namespaces.

**Comment by reilldesign** [comment]
1. After the installation I get the following error

Internal server error


2. After clicking on dashboard, the following stack is displayed

Es ist ein Fehler aufgetreten!

    0 Class "Joomgallery\Component\Joomgallery\Administrator\Helper\JoomHelper" not found 

Call Stack
# 	Function 	Location
1 	() 	JROOT/plugins/system/joomowner/src/Extension/JoomgalleryOwner.php:119
2 	Joomgallery\Plugin\System\Joomowner\Extension\JoomgalleryOwner->__construct() 	JROOT/plugins/system/joomowner/services/provider.php:33
3 	Joomla\DI\ServiceProviderInterface@anonymous/mnt/web307/e1/94/5107694/htdocs/poollounge/plugins/system/joomowner/services/provider.php:21$14->{closure}() 	JROOT/libraries/vendor/joomla/di/src/ContainerResource.php:172
4 	Joomla\DI\ContainerResource->getInstance() 	JROOT/libraries/vendor/joomla/di/src/Container.php:95
5 	Joomla\DI\Container->get() 	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:177
6 	Joomla\CMS\Application\CMSApplication->loadExtension() 	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:99
7 	Joomla\CMS\Application\CMSApplication->bootPlugin() 	JROOT/libraries/src/Plugin/PluginHelper.php:232
8 	Joomla\CMS\Plugin\PluginHelper::import() 	JROOT/libraries/src/Plugin/PluginHelper.php:192
9 	Joomla\CMS\Plugin\PluginHelper::importPlugin() 	JROOT/libraries/src/Application/CMSApplication.php:765
10 	Joomla\CMS\Application\CMSApplication->initialiseApp() 	JROOT/libraries/src/Application/AdministratorApplication.php:321
11 	Joomla\CMS\Application\AdministratorApplication->initialiseApp() 	JROOT/libraries/src/Application/AdministratorApplication.php:174
12 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:306
13 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/includes/app.php:58
14 	require_once() 	JROOT/administrator/index.php:32




3. After renaming the plugin

plugins/system/joomowner

I have access to the Joomal backend again


4. When I try to call the JoomGallery backend I get the following stack

<h1>Es ist ein Fehler aufgetreten!</h1>
                        <blockquote class="blockquote">
                            <span class="badge bg-secondary">0</span>
                            Class 
"Joomgallery\Component\Joomgallery\Administrator\MVC\MVCFactoryProvider"
 not found                        </blockquote>
                                                    <div>
                                <h2 id="caption">Call Stack</h2>

# | Function | Location
-- | -- | --
1 | () | JROOT/administrator/components/com_joomgallery/services/provider.php:48
2 | Joomla\DI\ServiceProviderInterface@anonymous/mnt/web307/e1/94/5107694/htdocs/poollounge/administrator/components/com_joomgallery/services/provider.php:35$10->register() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:145
3 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:51
4 | Joomla\CMS\Application\CMSApplication->bootComponent() | JROOT/libraries/src/Component/ComponentHelper.php:361
5 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
6 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
7 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
8 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
9 | require_once() | JROOT/administrator/index.php:32

**Comment by rowi68** [comment]
Deleting file autoload_psr4.php  and refreshing the page was successful, but after clicking "Migration" same result as @AlexanderSupp

2024-09-16_16h01_09

**Comment by Elfangor93** [comment]
@rowi68, @AlexanderSupp You are right, there was an issue in the installer script. Should be fixed now.

**Comment by reilldesign** [comment]
The pull request was installed without any problems and the access rights of the categories work successfully.

The access rights of the images are always overwritten by the category rights. How should these be tested?


No thumbnails are displayed in the image manager.

When clicking on an image in the image manager, the following error message appears


3 arguments are required, 2 given

# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/src/Language/Text.php:281
2 | sprintf() | JROOT/libraries/src/Language/Text.php:281
3 | Joomla\CMS\Language\Text::sprintf() | JROOT/plugins/editors/codemirror/layouts/editors/codemirror/codemirror.php:62
4 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
5 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:76
6 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/plugins/editors/codemirror/src/Provider/CodeMirrorProvider.php:164
7 | Joomla\Plugin\Editors\CodeMirror\Provider\CodeMirrorProvider->display() | JROOT/libraries/src/Editor/Editor.php:211
8 | Joomla\CMS\Editor\Editor->display() | JROOT/libraries/src/Form/Field/EditorField.php:251
9 | Joomla\CMS\Form\Field\EditorField->getInput() | JROOT/libraries/src/Form/FormField.php:1056
10 | Joomla\CMS\Form\FormField->renderField() | JROOT/libraries/src/Form/Form.php:536
11 | Joomla\CMS\Form\Form->renderField() | JROOT/administrator/components/com_joomgallery/tmpl/image/edit.php:108
12 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:416
13 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:204
14 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_joomgallery/src/View/Image/HtmlView.php:100
15 | Joomgallery\Component\Joomgallery\Administrator\View\Image\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
16 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_joomgallery/src/Controller/DisplayController.php:119
17 | Joomgallery\Component\Joomgallery\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
18 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
19 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/administrator/components/com_joomgallery/src/Dispatcher/Dispatcher.php:32
20 | Joomgallery\Component\Joomgallery\Administrator\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
21 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
22 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
23 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
24 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
25 | require_once() | JROOT/administrator/index.php:32

**Comment by Elfangor93** [comment]
>But I found another issue:
It is possible to rename the alias of a category only once. After that you could not delete this category anymore, because the old category is tried to be deleted (which not existing anymore).
If I try to rename second or third time appears message " Folder could not be renamed".
When you then press save button second time, a new categorie folder will be created in /images/joomgallery...

There is already an issue for that:
https://github.com/JoomGalleryfriends/JG4-dev/issues/236

**Comment by reilldesign** [comment]
TinyMCE is the default editor

**Comment by Elfangor93** [comment]
> The access rights of the images are always overwritten by the category rights.

There was a problem that all the Permissions-Tabs always showed the category permissions. Therefore it looked like category permissions were applied to images as well, as if they would overwrite them. This should be fixed now.

**Comment by MrMusic** [comment]
Test im Frontend, z.B. als "Publisher".
Joomla 5.1.4

Test: Anlegen einer neuen Kategorie.
Beim speichern kommt die Meldung:
`Save failed with the following error: Field 'created_time' doesn't have a default value`

Test: Editieren einer Kategorie
Beim Speichern kommt folgende Meldung:
`Save failed with the following error: Please provide a valid record ID, alias or filename.`
Kein Call-Stack

Wenn man versucht die Kategoriebeschreibung zu ändern, kommt zudem folgender Fehler:
```
0 Joomla\CMS\Form\Field\EditorField::filter field `description` calls a deprecated filter class JComponentHelper, the class needs to be namespaced use \Joomla\CMS\Component\ComponentHelper instead or activate the backward compatible plugin. 
1 	() 	JROOT\libraries\src\Form\FormField.php:1105
2 	Joomla\CMS\Form\FormField->filter() 	JROOT\libraries\src\Form\Form.php:1047
3 	Joomla\CMS\Form\Form->filter() 	JROOT\libraries\src\Form\Form.php:991 
```
Test: Löschen von Kategorien
Löschen einer Kategorie aus der Category view heraus:
Im PopUp erscheinen die Sprachkonstanten `COM_JOOMGALLERY_COMMON_DELETE_CATEGORY_TIPCAPTION` und `COM_JOOMGALLERY_COMMON_ALERT_SURE_DELETE_SELECTED_ITEM`
Beim ausführen kommt folgende Meldung:
```
503 Removing category not possible. Use categoryform controller instead.
Call Stack:
1 	() 	JROOT\components\com_joomgallery\src\Controller\CategoryController.php:148
2 	Joomgallery\Component\Joomgallery\Site\Controller\CategoryController->remove() 	JROOT\libraries\src\MVC\Controller\BaseController.php:730
3 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:143 
```
Beim löschen aus der List of Categories funktioniert es dagegen korrekt (anderes PopUp).

Test: Editieren von Bildern
Editieren Button wird nicht angezeigt wenn nur "Edit own"-Berechtigung vergeben ist.

Beim Speichern des Bildes kommt folgende Meldung:
```
0 Class "Joomgallery\Component\Joomgallery\Site\Controller\JoomHelper" not found
Call Stack:
1 	() 	JROOT\components\com_joomgallery\src\Controller\ImageformController.php:104
2 	Joomgallery\Component\Joomgallery\Site\Controller\ImageformController->save() 	JROOT\libraries\src\MVC\Controller\BaseController.php:730
3 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:143
``` 

Test: Löschen von Bildern
Löschen-Button wird nicht angezeigt wenn nur "Delete own"-Berechtigung vergeben ist.

Beim löschen eines Bildes kommt folgende Meldung
```
0 Class "Joomgallery\Component\Joomgallery\Site\Controller\JoomHelper" not found
Call Stack:
1 	() 	JROOT\components\com_joomgallery\src\Controller\ImageformController.php:266
2 	Joomgallery\Component\Joomgallery\Site\Controller\ImageformController->remove() 	JROOT\libraries\src\MVC\Controller\BaseController.php:730
3 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:143
```

**Comment by Elfangor93** [comment]
@MrMusic The edit form views in the frontend may not work. But this is not related to a bug in the ACL or any processing logic but the form templates. In order to make them work one has to update the form templates. This will not be done in this PR.

**Comment by Elfangor93** [comment]
>Editieren Button wird nicht angezeigt wenn nur "Edit own"-Berechtigung vergeben ist.
Löschen-Button wird nicht angezeigt wenn nur "Delete own"-Berechtigung vergeben ist.

Unfortunately, this check was not yet available. to make this possible, i will have to adjust the access service again quite a lot. Lets hope, that I dont break anything else by applying this check.

**Comment by MrMusic** [comment]
New Test in the backend, found the following problems:

**Category Permission**
Create Own 
Creating a subcategory is not possible if only 'Create own' Permission is 'Allowed'.

Delete Own
No delete button is displayed.
If `if($this->getAcl()->checkACL('delete', 'category'))` is deactivated in the view file, the delete button appears.
The delete function itself then works as expected.
I think you can always leave the delete button displayed.

**Image Permission**
Upload in Own
Upload not possible if only 'Upload in Own' Permission is 'Allowed'.

Delete Own
No delete button is displayed.
If `if($this->getAcl()->checkACL('delete', 'image', 1, true))` is deactivated in the view file, the delete button appears.
The delete function itself then works as expected.
I think you can always leave the delete button displayed.

**Comment by Elfangor93** [comment]
Please reinstall this PR before testing again. There was a bug in creating categories. To avoid compatibility please reinstall.

**Comment by MrMusic** [comment]
New Test in the backend after new installation.
Problems:

**Category Permission**
Delete Own
No delete button is displayed.
If `if($this->getAcl()->checkACL('delete', 'category'))` is deactivated in the view file, the delete button appears.
I think you can always leave the delete button displayed.

**Image Permission**
Upload in Own
Upload not possible if only 'Upload in Own' Permission is 'Allowed'.

Delete Own
No delete button is displayed.
If `if($this->getAcl()->checkACL('delete', 'image', 1, true))` is deactivated in the view file, the delete button appears.
I think you can always leave the delete button displayed.
Second problem: deleting images is only possible if Delete Permission is also 'Allowed' for the category.

Edit Own
Edit not possible if only 'Edit Own' Permission is 'Allowed'.
So the same problem as with 'Upload in Own' and 'Delete Own'...

**Comment by Elfangor93** [comment]
> The upload is not possible if only ‘Upload in own’ is activated. 

I can not reproduce this. What are your exact configurations?

I can see that the permissions in the category from view, tab image permissions are calculated wrong but the real ACL is working correctly. So its just a GUI problem I guess...
grafik

The thing is to fix this GUI problem there would be a huge work needed to refactor the whole permissions form field. If really needed, I would like to do that in another PR.

**Comment by MrMusic** [comment]
>I can not reproduce this. What are your exact configurations?

Test:
Create a new category, eg. 'abc'. Set owner = 'Publisher' (Member of Publisher group).
Set the 'Image Permissions' as in this screenshot (Upload in own = Allowed) for group 'Publisher'.
ACL-image-upload-in-own

Log in as 'Publisher'.
Try Upload in Category 'abc'.
Expected result: Upload is possible as this has been set for this category explicitly.
Actual result: Error 'Save not permitted'
ACL-image-upload-in-own-error
Note: If set the Permission 'Upload = Allowed' the upload works.

**Comment by MrMusic** [comment]
>@MrMusic I had to move the "Upload" and "Upload in Own" to the Category Permission tab. Otherwise the logic in the Access service will not work anymore. Should be fixed now.

Thanks, in Backend it works good now.
In Frontend when calling the category view:
```
1 Error in your input command: parent_pk (4th argumant) has to be set to check permission for the action 'add' on an item within a nested group of assets. Please set parent_pk to 'true' and make sure that the specified primary key corresponds to the category you want to add to. 

Call Stack
# 	Function 	Location
1 	() 	JROOT\administrator\components\com_joomgallery\src\Service\Access\Access.php:199
2 	Joomgallery\Component\Joomgallery\Administrator\Service\Access\Access->checkACL() 	JROOT\components\com_joomgallery\tmpl\category\default_cat.php:91
3 	include() 	JROOT\libraries\src\MVC\View\HtmlView.php:416
4 	Joomla\CMS\MVC\View\HtmlView->loadTemplate() 	JROOT\components\com_joomgallery\tmpl\category\default.php:33 
```

**Comment by MrMusic** [comment]
>Yes. This PR does not include the frontend form views as many other things in this views are not yet correct.
Thats why I added the PR to deactivate the frontend form views.

@Elfangor93: I don't mean the form for editing the category, but the normal 'Category view' that guests also call up.

**Comment by MrMusic** [comment]
Thanks for the fix.
I have tested this PR ✅ successfully.
Thank you very much.

**Pull request merged**
