### PR TITLE
Overhaul of FileManager service

### PR DESCRIPTION
**Pull request by Elfangor93**
## What is this service for

The FileManager service will be used to handle the files and folders created in the filesystem. I offers methods to perform processes (create, delete, check, move) on image files and folders.

**This is a overhaul of PR #26.**

The usage of the FileManager is exactly the same as before but now with a complete new filesystem service. The new filesystem service support the filesystem adapter provider of com_media. Meaning that different filesystems can be used based on which filesystem plugins you have installed.

## What are filesystem plugins

Filesystem plugins are a new type of plugins introduced with Joomla 4. They allow Joomla to communicate with different filesystems. In the Joomla core only one filesystem plugin is preinstalled to do operations with files on the local hosted filesystem:
grafik

There are already several additional filesystem plugins available allowing you to operate with files on other, even not locally hosted filesystems like gDrive, OneCloud, Amazon S3, ...
- https://extensions.joomla.org/extension/amazon-s3-filesystem/
- https://extensions.joomla.org/extension/dpmedia/
- https://www.joomlacontenteditor.net/downloads/plugins/server-filesystem
- https://extensions.joomla.org/extension/google-cloud-storage/

This results that JoomGallery start to support multiple filesystems with this PR without the need of writing code by ourselfs.

## How to use this service

See PR #26

## How to test this service

See PR #26. Everything should work the same as before. You can even use the operations in the GUI to perform the tests.

Affected opertaions:
- create Images
- delete Images
- check Images
- move Images
- copy Images
- create Category
- delete Category
- check Category
- move Category
- copy Category
- get image path
- get category path

### CODE REVIEW

**Comment by reni68** [comment]
Do I still have to do everything from PR #26? Including the adjustments in the HtmlView.php?

Because I only get error messages when saving an image - regardless of whether it's GD Library or ImageMagick.

**Comment by Elfangor93** [comment]
You dant have to do the scriptic testing with the HtmlView.php if you dont want. Most of the operations are also available using the GUI. Please comment here if you find an issue. Please follow these instructions when reporting an issue such that I can reproduce the error and fix it.
Instructions:
https://github.com/JoomGalleryfriends/JG4-dev#testing

**Comment by AlexanderSupp** [comment]
Yesterday I tested in my environment by DomainFactory. Today I'm checking with WampServer on PC Win 11.
I uninstalled all components of JG4. Then I installed only Overhaul of File Manager (adaptor provider).
The first tests show, that Save & New did not work. Now with a special Info, see screenshot below.

Screenshot 2023-03-21 110425

This Error Message detect only by Save & New. All other operations with Categories work correct.

Screenshot 2023-03-21 111132

Now the result to store an image.

Screenshot 2023-03-21 110655

Screenshot 2023-03-21 110808


Screenshot 2023-03-21 111022

**Comment by reni68** [comment]
I probably can't test this PR since I don't have any non-locally hosted filesystems available.
Locally stored images terminate with this error message when uploaded:
Screenshot_20230320_1
Tested on Linux with XAMPP, Joomla 4.2.9 and PHP 8.0.15.

**Comment by Elfangor93** [comment]
There was an error in the installation script. Your reported errors should be gone now...

**Comment by Elfangor93** [comment]
>Then I installed main, DE-Language, Save & New, Overhaul of File Manager (adaptor provider). The first tests show, that Save & New did not work.

@AlexanderSupp you are messing up things. You should not install multiple branches on top of each other. It is obvious that Save & New does not work on this branch since it was fixed in another PR!
With messing things up you are making my life harder. Please test one PR after another!!

**Comment by Elfangor93** [comment]
> I probably can't test this PR since I don't have any non-locally hosted filesystems available.

Locally hosted means in that case, that your files are stored on the same device where Joomla is running. This represents the standard case.

**Comment by AlexanderSupp** [comment]
> > Then I installed main, DE-Language, Save & New, Overhaul of File Manager (adaptor provider). The first tests show, that Save & New did not work.
> 
> @AlexanderSupp you are messing up things. You should not install multiple branches on top of each other. It is obvious that Save & New does not work on this branch since it was fixed in another PR! With messing things up you are making my life harder. Please test one PR after another!!

@Elfangor93 Sorry, I don't want to make your life harder. I forgot the specific software development strategy with GitHub in combination with Joomla. I vow to get better.

**Comment by AlexanderSupp** [comment]
Uninstalled JG4, installed adapter-provider. Tested with Win 11, WampServer with JG4 Default Settings.
Config, Tags, Categories, Images works as expected. Fine.
I would now like to test access to the Microsoft Cloud OneDrive or to my Synology NAS in the home network. Where can I read more about this?

**Comment by MrMusic** [comment]
Two things I have noticed:
1.
I have installed two filesystem plugins: 'DPMedia FTP' and 'Amazon S3'. Both are displayed in the Joomla Media Manager.
In the JoomGallery configuration, only the 'Local filesystem' still appears in the list of filesystems, not the other two.
2.
Even if I use the 'Local filesystem', no more images are displayed in the image manager. Also after installing the 'Sample data' no thumbs are shown anymore although they are actually present in the file system.

**Comment by MrMusic** [comment]
> I would now like to test access to the Microsoft Cloud OneDrive or to my Synology NAS in the home network. Where can I read more about this?

@AlexanderSupp You need a Joomla plugin to handle the access to OneDrive or the Synology NAS, but i don't know if it still exist?

**Comment by Elfangor93** [comment]
> In the JoomGallery configuration, only the 'Local filesystem' still appears in the list of filesystems, not the other two.

The list currently is hardcoded. A dynamic list will gollow later. So if you want to test other filesystems you have to use php code accessing the filemanager service directly.

**Comment by reni68** [comment]
My test today:
- I uninstalled and reinstalled the component
- Uploaded images - successfully:
Bild_Upload

- But images are not visible in the JoomGallery:
Images

- But you can delete anyway:
Image_delete

- In the filesystem the images are stored correctly:
Filesystem

Tested on Linux with XAMPP, Joomla 4.2.9 and PHP 8.0.15.

**Comment by Elfangor93** [comment]
> But images are not visible in the JoomGallery:

Can you post the nswer of the requests fetching the thumbnails?
You can do that using the network tab in your browser console...

**Comment by reni68** [comment]
> Can you post the answer of the requests fetching the thumbnails?
this?
Screenshot_20230322_1
278c.jpeg)

Or how do I get that exported?

**Comment by Elfangor93** [comment]
Oke I think I found the issue why images were not displayed in some environments. Can you please try again? Are they now showing up in your testing systems?

**Comment by reni68** [comment]
Yes, now the images and thumbnails are visible :-)
Great!
Screenshot_20230324_1
Screenshot_20230324_2

**Comment by MrMusic** [comment]
>Yes, now the images and thumbnails are visible :-)

Confirmed.

>I was able to test the following functions:
create Images, delete Images, move Images, copy Images, create Category, delete Category, move Category, copy Category

@eumel1602: Did you test uploading new images after moving categories?

For me the problem of issue https://github.com/JoomGalleryfriends/JG4-dev/issues/44 still exists.

**Comment by reni68** [comment]
> For me the problem of issue #44 still exists.

Yes, with me too and the "old" picture, which was moved with, is also no longer visible.

**Comment by Elfangor93** [comment]
All the other upload related bugs are solved?
Can they be closed?

**Comment by eumel1602** [comment]
> @eumel1602: Did you test uploading new images after moving categories?
> 
> For me the problem of issue #44 still exists.

Hello. I cannot confirm this error. this works for me with no problems. I tested it again now...

**Comment by Elfangor93** [comment]
Issue #44 will be solved within PR #86.

**Pull request merged**
