### PR TITLE
Improve configuration manager (by Elfangor)

### PR DESCRIPTION
**Pull request by Elfangor93**
This PR is a further development of the PR #9.

The following changes are made (same as PR #9):

- use the 'showon' feature where possible
- use layout 'joomla.form.field.radio.switcher' for 0/1 options

Additionally the following changes are made:

- new subform layout named "repeatable-config".
- subform layout used for Image processing settings (Table with modal containing settings).
- global_only parameter in config.xml (Settings which can only be changed in the Global Configuration).
- add default watermark file in configs.
- add config parameter jg_filesystem (Selection of filesystem used for image storage).
- Bugfix: Save, Delete, Update imagetype table through config form (Image processing).

### CODE REVIEW

**Comment by szepty-ziemi** [comment]
Radio switcher should have two colors:

No = red
Yes = green

obraz

Current behavior:

obraz

**Comment by szepty-ziemi** [comment]
Configuration Manager -> Configuration set -> General settings -> Upload

Show warning radio default option:

obraz

When clicking on it:

obraz

Then click again:

obraz

It doesn't return to default No state.

**Comment by szepty-ziemi** [comment]
ENV: https://prnt.sc/Qi06hS2mU4Qw

Issues: 

- https://github.com/JoomGalleryfriends/JG4-dev/pull/21#issuecomment-1157570037
- https://github.com/JoomGalleryfriends/JG4-dev/pull/21#issuecomment-1157570037

showon list that was tested:

✓ Configuration Manager -> Configuration set -> User settings -> General settings

COM_JOOMGALLERY_CONFIG_UR_UU_USERSPACE="Allow userspace"

✓ Configuration Manager -> Configuration set -> User settings -> Upload

COM_JOOMGALLERY_CONFIG_UR_UU_UPLOAD_SINGLE="Enable Single Upload"

✓ Configuration Manager -> Configuration set -> User settings -> Download

COM_JOOMGALLERY_CONFIG_UR_UD_DOWNLOAD="Offer Downloads"

✓ Configuration Manager -> Configuration set -> User settings -> Ratings

COM_JOOMGALLERY_CATMAN_ALLOW_RATING="Allow Rating"

✓ Configuration Manager -> Configuration set -> General settings -> Image processing

COM_JOOMGALLERY_CONFIG_SHOWOPTIONS="Show options" <- this constant is not used (instead there is hardcoded "Show settings text" https://prnt.sc/UjRaf4G5uMLt )

✓ Configuration Manager -> Configuration set -> General settings -> Image processing (modal)

COM_JOOMGALLERY_CONFIG_GS_IP_RESIZING="Resizing"
COM_JOOMGALLERY_CONFIG_DV_GS_ADD_WATERMARK="Add Watermark?"

✓ Configuration Manager -> Configuration set -> General settings -> Image processing (modal, watermark subform)

COM_JOOMGALLERY_CONFIG_DV_GS_WATERMARKSIZE="Watermark Size"

**Comment by szepty-ziemi** [comment]
ENV: https://prnt.sc/Qi06hS2mU4Qw

✓ global_only parameter in config.xml (Settings which can only be changed in the Global Configuration).
- Image Path -> Configuration Manager -> Configuration set -> General settings -> Image processing (modal)
- Filesystem - > Configuration Manager -> Configuration set -> General settings -> General settings

✓ add config parameter jg_filesystem (Selection of filesystem used for image storage).
- Filesystem - > Configuration Manager -> Configuration set -> General settings -> General settings

✓ default Global configuration settings can't be deleted
✓ Bugfix: Save, Delete, Update imagetype table through config form (Image processing) 
✓ subform layout used for Image processing settings (Table with modal containing settings)
✓ new subform layout named "repeatable-config"
✓ add default watermark file in configs.

**Comment by Elfangor93** [comment]
@MrMusic If you are happy with this revision of your PR #9, please merge this PR and close yours...

**Pull request merged**
