### PR TITLE
Fix approve button

### PR DESCRIPTION
**Pull request by Elfangor93**
Before this PR the approve button did not work korrectly. It was not possible to unapprove an image once it was approved using the images view.

With this PR this should work now.

### CODE REVIEW

**Comment by eumel1602** [comment]
Maybe I'm misunderstanding it but:
I can click the "Approved" button in the general image view (Image 1). This works (has always worked), if I edit in the single image I can't do that, there is no selection area (image 2)
If the "approved" button is to be regulated differently, please provide a brief description here
(Win 10 / J4.3.2. PHP 8.0
veroeffentlicht1
veroeffentlicht2

**Comment by Elfangor93** [comment]
Unapproving images in the lost view didnt work before this PR.

**Comment by eumel1602** [comment]
ok, i couldn't find any mistake

**Comment by MrMusic** [comment]
I have tested this item ✅ successfully. Thank you very much.

**Pull request merged**
