### PR TITLE
Justified layout, font, new styles and params added

### PR DESCRIPTION
**Pull request by reilldesign**
- A third category view layout (justified) and additional menu item parameters have been added.
- jg icon font has been added with the first icons (more to follow).
- Some adjustments to the category and image layout.
- New css loader and other improvements.

### CODE REVIEW

**Comment by AlexanderSupp** [comment]
I got the error message: There is no "com_joomgallery.jg-icon-font" asset of a "style" type in the registry. 
What is wrong in my installation?

**Comment by reilldesign** [comment]
@AlexanderSupp a file was missing. Please check the request again.

**Comment by AlexanderSupp** [comment]
The error message still exists.

Screenshot 2023-11-04 170827

Screenshot 2023-11-04 170847

**Comment by AlexanderSupp** [comment]
Screenshot 2023-11-04 171421

**Comment by AlexanderSupp** [comment]
This PR points to the code "main". Is this correct?

**Comment by AlexanderSupp** [comment]
Must "com_joomgallery.jg-icon-font" defined in joomla.asset.json ?

**Comment by MrMusic** [comment]
I think the 'fonts' folder is missing in joomgallery.xml

**Comment by reilldesign** [comment]
@MrMusic you're absolutely right, of course. I didn't notice this with my local installation. The xml file has been changed.

**Comment by AlexanderSupp** [comment]
I tried it again, and it doesn't work in my installation.
@MrMusic  Can you try it, you have more experience.
Thanks to all.

**Comment by AlexanderSupp** [comment]
After installation, in "C:\wamp64\www\Joomla\media\com_joomgallery" I found a file called "joomla.asset.json".
I don't know what it is, but I found here style definitions.
I found no definition for jg-icon-font.
In the root of the installation file, I also found a file called "joomla.asset.json".
Here I found the definition
{
      "name": "com_joomgallery.jg-icon-font",
      "type": "style",
      "uri": "com_joomgallery/jg-icon-font.css"
    },

Is this OK?
Keep in mind that I am a blind chicken to pick up a grain.

**Comment by AlexanderSupp** [comment]
I am happy to be a blind chicken. I added the style definition to "C:\wamp64\www\Joomla\media\com_joomgallery/joomla.asset.json" and it works. Now I continue the tests with this PR.

**Comment by AlexanderSupp** [comment]
Now I found similar errors like "There is no "com_joomgallery.justified" asset of a "script" type in the registry."
I wait with further tests until the next corrections.

**Comment by MrMusic** [comment]
@AlexanderSupp: Well done! You are absolutely right. The error is in the media/com_joomgallery/joomla.asset.json file, which has not been updated during installation.

@reilldesign: It seems that in your branch you have copied the updated joomla.asset.json into the main directory of JoomGallery instead into the directory 'media/com_joomgallery'.

**Comment by AlexanderSupp** [comment]
I installed the new version. It doesn't work.
So I analysed your JG4-dev-main.zip with the result, that media/com_joomgallery/joomla.asset.json has twice objects with this name (duplicate media/com_joomgallery in zip file). 
Screenshot 2023-11-06 173535

Now I merged manually 
{
      "name": "com_joomgallery.justified",
      "type": "script",
      "uri": "com_joomgallery/imgjust.min.js",
      "attributes": {
        "defer": true
      }
    },
{
      "name": "com_joomgallery.jg-icon-font",
      "type": "style",
      "uri": "com_joomgallery/jg-icon-font.css"
    },
    
into media/com_joomgallery/joomla.asset.json.
And this works.
I wish you good luck with struggling with GitHub. 
I continue the tests.

**Comment by MrMusic** [comment]
> has twice objects with this name (duplicate media/com_joomgallery in zip file).

Strange. Two folders with the same name. Interesting what github can do...

I woud recomment to revert your last commit https://github.com/reilldesign/JG4-dev/commit/f11990f3fdc71d5981398071bc0e5b5305e2bbb5
and after then i would make the changes manually in the file media/com_joomgallery/joomla.asset.json.

**Comment by AlexanderSupp** [comment]
I uninstalled JG4 and install the new version of this PR.
I prepared my test environment from the ground.
Furthermore, I added three separate menus for category view.
Screenshot 2023-11-09 174145

Each layout I changed the parameters step by step and called the menu twice to get a result.

**Grid Layout:**
Columns, everything works, 1-3 boxes too large, for use this make no sense, because image to small. 4 - 6 very fine.
Image layout, none, boxed, everything works fine.
Title alignment works fine. My proposal is an additional parameter, named NONE, because in many installations the internal image name of the camera will be display and this make no sense. Better, is no Title.
Category view with subcategories works. And images also show perfect.
Screenshot 2023-11-09 174301

**Comment by AlexanderSupp** [comment]
**Masonry:**
Columns, everything works fine. Here 1-6 boxes usable.
Image layout, none, boxed, everything works fine.
Title alignment works fine. My proposal is an additional parameter, named NONE, because in many installations the internal image name of the camera will be display and this make no sense. Better, is no Title.
Category view with subcategories works. And images also show perfect.

**Comment by AlexanderSupp** [comment]
**Justified:**
That my favourite, because on a solid line all images presents with his original proportions.
Screenshot 2023-11-09 195720
Ideal Height is set to 100 and gap is 5.
Title alignment is left. As you see, the title is not displayed. That doesn't matte, because it would destroy the harmonic picture.
May be at this point a mouse over function would help.

Gap and ideal high works perfect.

Conclusion:
The features work fine. It is very difficult to test all situations. If I click to a category, the system branch to a standard view which is not one of the layout defined.
If I activate in the menu List Categories, and then I click to a category, it would be great if there is a defined layout will be present (and not any standard).

**Comment by MrMusic** [comment]
@reilldesign  The new layouts looks really great - thank you!

Questions about the next steps:
Will there still be an overlay effect (mouseover) for the masonry layout (or for all layouts)?
Global parameters for all categories in the configuration: will they still come in this PR or should they come in a new PR?

**Comment by reilldesign** [comment]
@MrMusic just fixed the hover problem with the last commit. The global configuration and menu parameters can then be set in the next pull request.

**Comment by AlexanderSupp** [comment]
I installed this last fix over the previous installation of this PR.
The hover function works fine with view justified.
Names of categories and images are displayed correct.
This PR is ready to merge into main.

I see forward to continue the tests with additional features in the next PR.
Thank you.

**Comment by AlexanderSupp** [comment]
I installed the new code over the old version without uninstall.
I can't find any irregularity things.
Thank you for implementation of "Title Alignment = None". It also works fine.

**Comment by Elfangor93** [comment]
Thank you very much  ✅

**Pull request merged**
