### PR TITLE
Fix delete empty category

### PR DESCRIPTION
**Pull request by MrMusic**
Possible Fix for issue https://github.com/JoomGalleryfriends/JG4-dev/issues/162

Before this fix: 
Deleting a empty category does not delete the folder in the filesystem.

After this fix: 
The folder in the filesystem shoud be deleted.

### CODE REVIEW

**Comment by rowi68** [comment]
I have tested this item ✅ successfully.
If deleting empty category, folder in the filesystem is also deleted...

**Comment by AlexanderSupp** [comment]
See my test results in Joomla 5.0 documented in issue https://github.com/JoomGalleryfriends/JG4-dev/issues/162
When this issue here is solved, is this also in Joomla 5.0 solved?

**Comment by MrMusic** [comment]
>When this issue here is solved, is this also in Joomla 5.0 solved?

Unfortunately, it looks to me as if Joomla 5 is adding further problems.
Example: Deleting categories under Joomla 5: In line 1103 of FileManager.php there is the following line: `if(\is_object($cat) && $cat instanceof \Joomla\CMS\Object\CMSObject && isset($cat->path))`.
The problem here is `$cat instanceof \Joomla\CMS\Object\CMSObject`. In Joomla 4.4 this was still valid but in Joomla 5.0 it is not anymore. I don't know why this is so and how to fix the problem. 
Simply removing `$cat instanceof \Joomla\CMS\Object\CMSObject` at this point would only be a temporary workaround. This code is used in many other places.
We'll have to wait what @Elfangor93 means about.

**Comment by AlexanderSupp** [comment]
> We'll have to wait what @Elfangor93 means about.

Thank you. Hopefully Joomla 5 won't be a major construction site.

**Comment by Elfangor93** [comment]
Yes, I know. CMSObject is removed with Joomla 5.
I can explain you that on the next meeting...

**Comment by AlexanderSupp** [comment]
Testing with Joomla 4.3.4, PHP 8.1.13, mysql 8.0.31.
I can confirm the result from @rowi68.
PR works successfully and is ready to merge into main.

**Comment by Elfangor93** [comment]
If I am informed correctly CMSObject is replaced with Registry. Maybe you could exchange the is instance of...

**Comment by MrMusic** [comment]
>If I am informed correctly CMSObject is replaced with Registry. Maybe you could exchange the is instance of...

Simply replacing `instanceof \Joomla\CMS\Object\CMSObject` with `instanceof \Joomla\Registry\Registry` unfortunately does not fix the error.

**Comment by MrMusic** [comment]
Changes:
- 'instanceof' removed
- function deleteCategory changed
- Removed conversion of the first letter to uppercase. Because: with some errors the name of the folder is displayed. The first letter is always converted to uppercase (ucfirst) although I had intentionally entered lowercase letters. To avoid such confusion I have removed this conversion in the FileManager.php

The following should now work in J4 and J5:
- delete a category - if empty
- error message if the category still contains images or subcategories
- There remains a possible 'ToDo': The possibility to delete categories that still have content (force_delete): But this would probably require major changes.

**Comment by AlexanderSupp** [comment]
Uninstalled JG4 and installed this PR into Joomla 5.0
Screenshot 2023-11-14 183938

I built up all data from scratch.
I try to reproduce the issue #162 
errors are gone. Everything fine.
No problem with CMSObject.
I try to delete a category with content.
Response correct: Category-Folder with name 'wanderboys' could not be deleted because there are still files and subfolders in it.
I delete all images and repeat the catalogue delete. Everything fine.

It seems that this PR is ready to merge into main.
However, I continue my tests with this 5.0 installation.

**Comment by rowi68** [comment]
I can confirm result from @AlexanderSupp.
Successfully tested with J4 and J5  :+1:

**Comment by Elfangor93** [comment]
> 'instanceof' removed

I am not satisfied with this quick fix. It does not solve the problem but suppresses the negative effects. I will start working on a PR removing CMSObject from our extension anyway soon. With this the error will be properly fixed.

**Comment by AlexanderSupp** [comment]
Is it possible to merge this PR now into main? And then close this PR, and we wait of a new PR.
There are too many open PR, with label "needs testing".

**Pull request merged**
