### PR TITLE
Fix error during uninstallation

### PR DESCRIPTION
**Pull request by MrMusic**
Fix for issue https://github.com/JoomGalleryfriends/JG4-dev/issues/127

Thanks for reporting this.

### CODE REVIEW

**Comment by ThomasFinnern** [comment]
Tested successfuly

**Comment by eumel1602** [comment]
test ok

**Comment by MrMusic** [comment]
@Elfangor93  can this PR merged?
I think it would be important to be able to uninstall the component for further testing.

**Comment by Elfangor93** [comment]
Works principially. But it intruduces redundant code.
With this work around `empty($modules->children())` gets checked double. PR #129 solves the same issue but does it with a bit nicer code.

**Pull request closed without merging**
