### PR TITLE
Configuration manager

### PR DESCRIPTION
**Pull request by Elfangor93**
## What is this pull request for

Basic functionality of Configuration Manager realized. It is now possible to use all the buttons and functionalities of the Configuration Manager.
It is now possible to reset/export/import configuartion sets.

## How to test this  pull request

- Click all the buttons, links and try everything out that is possible with the GUI inside the Configuration Manager.

It is not ment to test if the configuration settings are correctly applied within the component. It is about to test the functionality of the config manager itself like
- Creating, deleting, copying Configuration sets
- Reset, Export, Import Configuration sets
- Changing settings and see if the changes were saved in the configuration set (deleting, adding, changing settings)
- List view functionality like filtering, searching, ordering, status change, ...

### CODE REVIEW

**Comment by eumel1602** [comment]
Good evening. I noticed three things during quick testing:
1. Whenever I save any configuration setting, the tabs always snap back to the default position. That means e.g.: I change something in the "user settings" under "uploads" after saving it is back at: "General settings" and Common settings"
2.a; It is not possible to copy a global configuration: Error: see picture
bildschirmabgriff


2 B; Saving the configuration "as a copy" is also not possible!
Error: danger
Saving failed. Error: Field 'jg_dynamicprocessing' doesn't have a default value

3. Even creating a new configuration with the "New" button does not work! Error message: "Save failed. Error: Field 'jg_replaceinfo' doesn't have a default value"

4. Question: If I want to create a new configuration and import an existing .json file for it, I can't find a button to load it directly from my hard drive

**Comment by Elfangor93** [comment]
@eumel1602 Issues 1-3 are now fixed. Please try again.

Regarding issue 4
>If I want to create a new configuration and import an existing .json file for it, I can't find a button to load it directly from my hard drive

It is done by purpose that you first have to create a new configuration set before importing settings into it.

**Comment by eumel1602** [comment]
> @eumel1602 Issues 1-3 are now fixed. Please try again.

Unfortunately "1." still not working for me!

The original "Global Configuration" cannot be "hidden" (even if there are others)
    and you cannot delete the original configuration! Is it correct that way?

**Comment by Elfangor93** [comment]
>The original "Global Configuration" cannot be "hidden" (even if there are others)
and you cannot delete the original configuration! Is it correct that way?

Yes thats on purpose.

**Comment by Elfangor93** [comment]
>Whenever I save any configuration setting, the tabs always snap back to the default position. That means e.g.: I change something in the "user settings" under "uploads" after saving it is back at: "General settings" and Common settings"

Is that a problem? What would be the benefit if you switch automatically back to the last open tab?

**Comment by eumel1602** [comment]
> Is that a problem? What would be the benefit if you switch automatically back to the last open tab?

Definitely! It's annoying here when testing, if you press individual switches and buttons and then have to click back to the position where you were before saving!
It gets really uncomfortable when I e.g. create a new gallery and go through different config. Click dots and want to see what changes! For this I have to press the save button and see what changes in the FE. If I then want to undo the setting quickly, I have to look for this setting again... If I see a lot of setting options that JG 3 has, I would go crazy... Of course, for a setting change where I know what will happen, it does not matter...

**Comment by eumel1602** [comment]
I don't know if relevant:
"General settings" -> tab: "images processing" then images processing settings -> set "Ad Watermark" to Yes: then an incorrect language constant appears. see image:

**Comment by eumel1602** [comment]
Sorting by "title" does not work in the table. I have marked in the picture with a: "?" where it makes no difference to me. The sorting at the top right works!
In addition, when I tried to do the sorting via "title", I had a total crash once, you could change the config. Don't use Manager anymore, the error came up:
"   Unknown column a.imgtitle in where clause Unknown column a.imgtitle in where clause "

Only uninstalling and reinstalling the component JG4 could eliminate the error. But I couldn't reproduce this error a second time...

**Comment by Elfangor93** [comment]
> Definitely! It's annoying here when testing, if you press individual switches and buttons and then have to click back to the position where you were before saving!

I tried to realize that feature. Unfortunately its not easy to implement. I give up developing this feature after mor than 10 hours of coding and not succeeding.

**Comment by Elfangor93** [comment]
@eumel1602 Thanks for testing. Your found issues should be solved now.

**Comment by MrMusic** [comment]
>I tried to realize that feature. Unfortunately its not easy to implement. I give up developing this feature after mor than 10 hours of coding and not succeeding

I did a quick search and found that saving the active tab (function saveActiveTab) in Joomla is done in file 'tabs-state.js'.
Maybe this helps?

**Comment by eumel1602** [comment]
> > I tried to realize that feature. Unfortunately its not easy to implement. I give up developing this feature after mor than 10 hours of coding and not succeeding
> 

I'm sorry I gave you so much work. I didn't realize it was such a big problem. This function already exists in the J3 gallery or does it work there.
But maybe we're talking past each other. In our meeting on 1.11. Can we talk about that again...
Otherwise, THANK YOU for your effort

**Comment by Elfangor93** [comment]
Issue found. Once created dynamic image processing settings can not be deleted anymore. So delete button does not work here...
grafik

**Comment by eumel1602** [comment]
I downloaded the latest version again today.
Overall, I couldn't find any more errors.
Also the problem with the (function saveActiveTab) seems to be fixed! It works fine for me now!

One thing I noticed:
If I want to load a data backup with "import" into a configuration and do not select a .json file! -> Then click "import": If the following error occurs (see picture):


Tested with Joomla 4.2.4 and php 7.4.x WINDOWS
bildschirmabgriff

**Comment by szepty-ziemi** [comment]
Regarding the issue with image processor dropdown:

obraz

ENV: https://prnt.sc/kzL9CeWgJwRC

**Comment by AlexanderSupp** [comment]
As discussed yesterday i deinstalled JG4 and installed only config-manager (JG4-dev-config-manager.zip).
Also i changed the language to english. System Manage Languages Default English Site and Admin.
The result was, that i see no field names in any function part. 
So i changed back to System Manage Languages Default German Site and Admin.
Now i see all field names, but the english names.
However, i continue the testing with this status.
Screenshot 2022-11-02 123451 default language english
Screenshot 2022-11-02 123751 default language german

**Comment by AlexanderSupp** [comment]
Attached my configuartion:
[systeminfo-2022-11-02T12 49 50+01 00.txt](https://github.com/JoomGalleryfriends/JG4-dev/files/9920896/systeminfo-2022-11-02T12.49.50%2B01.00.txt)

**Comment by AlexanderSupp** [comment]
Reminder as discussed 11/01/2022 regarding Image Processor.
Image-Processor-Field-On-Entry-Screenshot 2022-11-03 124011
Image-Processor-Field-On-Entry-Screenshot 2022-11-03 124011
Image-Processor-Field-After-Click-Screenshot 2022-11-03 124151
Image-Processor-Field-After-Click-Screenshot 2022-11-03 124151
Image-Processor-After-Select-GD-Library-and-More-Screenshot 2022-11-03 124419
Image-Processor-After-Select-GD-Library-and-More-Screenshot 2022-11-03 124419

Part of sysinfo:
=============
	gd
	=============
	GD Support: enabled
	GD headers Version: 2.3.3
	GD library Version: 2.3.3
	FreeType Support: enabled
	FreeType Linkage: with freetype
	GIF Read Support: enabled
	GIF Create Support: enabled
	JPEG Support: enabled
	PNG Support: enabled
	WBMP Support: enabled
	XPM Support: enabled
	XBM Support: enabled
	WebP Support: enabled
	BMP Support: enabled
	AVIF Support: enabled
	TGA Read Support: enabled

		=============
		gd.jpeg_ignore_warning
		=============
		Local Value: 1
		Master Value: 1

=============
	imagick
	=============
	imagick module: enabled
	imagick module version: 3.7.0
	imagick classes: Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
	Imagick compiled with ImageMagick version: ImageMagick 6.9.12-34 Q16 x86_64 2021-12-22 https://imagemagick.org
	Imagick using ImageMagick library version: ImageMagick 6.9.12-63 Q16 x86_64 17457 https://legacy.imagemagick.org
	ImageMagick copyright: (C) 1999 ImageMagick Studio LLC
	ImageMagick release date: 2022-09-11
	ImageMagick number of supported formats:: 245
	ImageMagick supported formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV

		=============
		imagick.allow_zero_dimension_images
		=============
		Local Value: 0
		Master Value: 0

		=============
		imagick.locale_fix
		=============
		Local Value: 0
		Master Value: 0

		=============
		imagick.progress_monitor
		=============
		Local Value: 0
		Master Value: 0

		=============
		imagick.set_single_thread
		=============
		Local Value: 1
		Master Value: 1

		=============
		imagick.shutdown_sleep_count
		=============
		Local Value: 10
		Master Value: 10

		=============
		imagick.skip_version_check
		=============
		Local Value: 1
		Master Value: 1

**Comment by Elfangor93** [comment]
I am setting up a Linux testing environment with xdebug to debug the problem with the dropdown.

**Comment by Elfangor93** [comment]
Image processor dropdown field should now also work on linux systems.

**Comment by szepty-ziemi** [comment]
I confirm Alexander's result:

obraz

**Comment by Elfangor93** [comment]
Yes, sorry I inserted a typo in the filename... Should work now.

But there are still the two things left to be fixed:
- Note modal opens when pressing enter in any text field
- Dynamic processing setting rows can not be deleted once they are created

**Comment by szepty-ziemi** [comment]
Should folders temp and ftp_upload be created while Joomgallery is installed? Path is predefined here:

obraz

But after installation there is no temp/ftp_upload

obraz

It needs to be created manually? Or maybe rather point to general tmp folder, in Joomla! ROOT?

ENV: https://prnt.sc/g2QXqk4PvUwL

**Comment by szepty-ziemi** [comment]
We have bunch of untranslated language constants:

<option value="0" selected="selected">No Replacement</option>
	<option value="COMMENT">Comment</option>
	<option value="IFD0-270">COM_JOOMGALLERY_IFD0_IMAGEDESCRIPTION (exif)</option>
	<option value="EXIF-37510">COM_JOOMGALLERY_SUBIFD_USERCOMMENT (exif)</option>
	<option value="IFD0-315">COM_JOOMGALLERY_IFD0_ARTIST (exif)</option>
	<option value="IFD0-33432">COM_JOOMGALLERY_IFD0_COPYRIGHT (exif)</option>
	<option value="IFD0-306">COM_JOOMGALLERY_IFD0_DATETIME (exif)</option>
	<option value="EXIF-36867">COM_JOOMGALLERY_SUBIFD_DATETIMEORIGINAL (exif)</option>
	<option value="EXIF-36868">COM_JOOMGALLERY_SUBIFD_DATETIMEDIGITIZED (exif)</option>
	<option value="IPTC-205">COM_JOOMGALLERY_IPTC_TITLE (iptc)</option>
	<option value="IPTC-2105">COM_JOOMGALLERY_IPTC_HEADLINE (iptc)</option>
	<option value="IPTC-2120">COM_JOOMGALLERY_IPTC_DESCRIPTION (iptc)</option>
	<option value="IPTC-240">COM_JOOMGALLERY_IPTC_INSTRUCTIONS (iptc)</option>
	<option value="IPTC-285">COM_JOOMGALLERY_IPTC_CREATORSJOBTITLE (iptc)</option>
	<option value="IPTC-280">COM_JOOMGALLERY_IPTC_CREATOR (iptc)</option>
	<option value="IPTC-225">COM_JOOMGALLERY_IPTC_KEYWORDS (iptc)</option>
	<option value="IPTC-2116">COM_JOOMGALLERY_IPTC_COPYRIGHTNOTICE (iptc)</option>
	<option value="IPTC-2110">COM_JOOMGALLERY_IPTC_CREDITLINE (iptc)</option>
	<option value="IPTC-2115">COM_JOOMGALLERY_IPTC_SOURCE (iptc)</option>
	<option value="IPTC-2122">COM_JOOMGALLERY_IPTC_DESCRIPTIONWRITER (iptc)</option>
	<option value="IPTC-255">COM_JOOMGALLERY_IPTC_DATECREATED (iptc)</option>
	<option value="IPTC-292">COM_JOOMGALLERY_IPTC_SUBLOCATIONLEGACY (iptc)</option>

Here:

obraz

**Comment by szepty-ziemi** [comment]
Once added "Use image metadata" can't be removed.

1. Go to General settings -> Uploads
2. Create three rows of settings in Use image metadata
3. Save

BTW as I reported in previous post, those options ware untranslated language constants. After setting and save they become translated.

4. Remove all settings row in Use image metadata
5. Save

Result:

Settings row are not deleted:

https://www.youtube.com/watch?v=BR8ZVzjbmwM

**Comment by Elfangor93** [comment]
> Should folders temp and ftp_upload be created while Joomgallery is installed?

This is a requisite from JoomGallery 3
grafik
I have taken over without giving it much thought. 

Generally in JoomGallery 4 there is no dedicated temp folder anymore. The temp folder of joomla will be used instead. So we could change the path to "administrator/components/com_joomgallery/ftp_upload/". But I think I will implement that when I implement the FTP uload method. It does not have any relevance for now.

**Comment by Elfangor93** [comment]
Maybe we should mark all configuration fields which currently do not have any effects. Currently there are many settings that are not yet taken into account anywhere in the code.
So they can be tested as soon as the corresponding functionality is available.
What do you thick?

**Comment by Elfangor93** [comment]
>Warnings for not present metadata while uploading.

I will not address this issue in this PR. So I added an issue (#53) to the repo not to forget about this.

**Comment by szepty-ziemi** [comment]
> Maybe we should mark all configuration fields which currently do not have any effects. Currently there are many settings that are not yet taken into account anywhere in the code. So they can be tested as soon as the corresponding functionality is available. What do you thick?

Yes, that will help a lot as there are many options and settings in Configuration Manager. Then we could focus on the ones that are connected to working features.

**Comment by Elfangor93** [comment]
Functionality added to PR:

- Ineffective, unused settings have now a red naming (label)
- Markup for advanced settings (settings with a serious impact on the functionality of the component). Labelled with an exclamation mark
- Markup for global only settings (settings which can only be changed in the Global Configuration set)

**Comment by AlexanderSupp** [comment]
Thanks for the clarification. This reduces our testing effort.
At the moment, it makes no sense to test the fields marked in red and those marked with an exclamation mark.

**Comment by Elfangor93** [comment]
There is still the problem of deleting rows in subforms. I still have no clue how to solve that. So please if anybody has an idea where the problem could be - tell me. I am out of ideas...

**Comment by AlexanderSupp** [comment]
Duplicate file in C:\Users\Alexa\Downloads\JG4-Installations\JG4-dev-config-manager\administrator\com_joomgallery\src\Field
ImgprocessorlistField.php
ImgProcessorListField.php
I don't know if that makes sense or bothers.

**Comment by AlexanderSupp** [comment]
Regarding my confusing field names and tab names (my comment from Nov 2, 2022), I found the reason.
In the Joomla root and admin root, I found after uninstalling the JoomGallery some language files. These were dated from September 2022. I deleted them manually.
Now it seems that all names are OK.
After installing the last dev-config-manager, I can test with languages de-DE and en-GB.
If I change the language to en-US, the field names will be confused. Instead of Published (i.e., in Tab for Tags), I see Permission.

**Comment by Elfangor93** [comment]
@MrMusic @szepty-ziemi Could one of you please double check if nothing messed up during rebase (force-push). If everything is ok, you can merge this PR.

**Comment by MrMusic** [comment]
I have noticed the following small problems:

1. Button 'Import': If the button Import was clicked without first selecting a file, an error occurs:
```
An error has occurred.

    0 Call to undefined method Joomgallery\Component\Joomgallery\Administrator\Model\ConfigModel::checkError() 
```

2. The subform 'use image metadata' (the field jg_replaceinfo) in the tab uploads is not deleted when resetting to default values.

3. The value 'No replacement' for the 'Source Metadata Field' is actually unnecessary, if not desired the entire line can be deleted.
In subform 'subform_imageinforeplace.xml' the line 
`<option value="0">COM_JOOMGALLERY_CONFIG_REPLACEVALUE_NONE</option>`
can be removed.

**Comment by szepty-ziemi** [comment]
Here is link to screen record: https://youtu.be/qwhL-okHcrg

1. Got to Global Settings -> Image processing tab
2. Add new image types
3. Click Save button

Result:

After save we skip to Permissions tab.

Expected result:

We should stay in the same tab "Image processing" or skip to "Common settings"

**Comment by szepty-ziemi** [comment]
There is wrong spelling in the field description:

obraz

**Comment by szepty-ziemi** [comment]
In my configuration I have GD library: https://prnt.sc/75dTeU2uEsl3
But when set in Global Configuration GD option and try to upload a file:

obraz

It says : GD Library not found. Make sure GD is activated in your PHP settings (php.ini).

But image is uploaded and created correctly.

Also in PHP information it says that WEBP support is enabled in GD. Trying to upload webp ends with:

obraz

**Comment by szepty-ziemi** [comment]
1. Selected IM and it seems that JG is detecting it correctly, even if I don't specify the path:
obraz
2. Then I'm trying to upload image and it fails:

Save failed with the following error:
Unsupported image filetype.

obraz

Previously I didn't have to specify the path (previous test versions) and IM worked fine.

https://prnt.sc/gjbixfIRq-Cn

**Comment by szepty-ziemi** [comment]
How numbering should work?

obraz

Numbering apply to file name or image title?

After uploading:

obraz

- original filename was "cover-male-default.png"
- was changed to "new_test_20230101_1024750690.png"
- while image is titled "New test"

I see current date in file name and number... Not sure how this numbering should work tho.

**Comment by szepty-ziemi** [comment]
Watermark field is working. In this PR there is no option to add it to the images?

obraz

Also I don't know how to test "Faster downsizing of images" I don';t see any difference in image processing when enabled/disabled.

**Comment by Elfangor93** [comment]
>How numbering should work?

Numbering will only work in multiple upload methods. So the setting is already used in the code, but the gui for multiple uploads is still missing.

**Comment by Elfangor93** [comment]
> We should stay in the same tab "Image processing" or skip to "Common settings"

Since we are using the tab behavior of the joomla core, this is nothing we can fix by ourselve. I guess this is a bug of multilayer tabs in the joomla core and since joomla core uses bootstrap 5 I guess this is a bug of bootstrap 5...

**Comment by Elfangor93** [comment]
> Watermark field is working. In this PR there is no option to add it to the images?

I can see that there is a problem in the IMGtools service in watermarking. I guess you can not see any watermark applying since the IMGtools service still has bugs.

**Comment by Elfangor93** [comment]
New issue opened: #61 Wrong debug message GD Library not found.
This issue will not be solved within this PR...

**Comment by Elfangor93** [comment]
New issue opened https://github.com/JoomGalleryfriends/JG4-dev/issues/62 Wrong error message Unsupported image filetype
This issue will not be resolved within this PR...

**Comment by Elfangor93** [comment]
> Also I don't know how to test "Faster downsizing of images" I don';t see any difference in image processing when enabled/disabled.

I guess this could be measured by the processing time or by debug the image creation with Xdebug. Then you see, if which method is used when resizing the image with GD.

**Comment by Elfangor93** [comment]
Thank you all for testing. I think we covered everything within the configuration manager itself. Testing for the settings to be applied in the component functionalities (like image creation) is not part of this PR. Take a look at the first comment. I updated it correspondingly.

**Comment by AlexanderSupp** [comment]
I think it's time to merge this function to main. Now.

**Comment by MrMusic** [comment]
Some great Improvements -Thank you very much!
I have tested this item ✅ successfully. Thank you very much.

**Pull request merged**
